import {FIQH_ART} from './fiqhArt';
import React,{useEffect,useState} from 'react';
import {normalizeArabicSearch} from './quranQuery';
import {shuffleOrder} from './NoorFeatures';
export type Lesson={id:string;section:string;title:string;text:string;evidence:string;ref:string;note?:string};
export const LESSONS:Lesson[]=[
{id:'islam',section:'الإسلام والإيمان',title:'أركان الإسلام',text:'الإسلام مبني على الشهادتين، وإقامة الصلاة، وإيتاء الزكاة، وصوم رمضان، وحج البيت لمن استطاع. تعلّم معنى الشهادتين والعمل بما تقتضيانه.',evidence:'حديث «بني الإسلام على خمس»',ref:'صحيح البخاري ٨ · صحيح مسلم ١٦'},
{id:'iman',section:'الإسلام والإيمان',title:'أركان الإيمان',text:'الإيمان بالله وملائكته وكتبه ورسله واليوم الآخر والقدر خيره وشره. الإحسان أن تعبد الله كأنك تراه، فإن لم تكن تراه فإنه يراك.',evidence:'حديث جبريل',ref:'صحيح مسلم ٨'},
{id:'conditions',section:'الصلاة',title:'شروط الصلاة',text:'من شروط صحة الصلاة دخول وقتها، والطهارة من الحدث، واجتناب النجاسة، وستر العورة، واستقبال القبلة عند القدرة، والنية. الشرط يسبق العبادة ويستمر فيها، بينما الركن جزء منها.',evidence:'الصلاة كتاب موقوت؛ الأمر بالطهارة واستقبال القبلة',ref:'النساء ١٠٣ · المائدة ٦ · البقرة ١٤٤',note:'تفاصيل ستر العورة وإزالة النجاسة وحالات العجز تختلف في بعض المذاهب؛ راجع باب شروط الصلاة في الموسوعة الفقهية بالدرر السنية.'},
{id:'pillars',section:'الصلاة',title:'الأركان والطمأنينة',text:'القيام في الفريضة للقادر، وتكبيرة الإحرام، والقراءة، والركوع، والرفع منه، والسجود، والجلوس بين السجدتين والطمأنينة والترتيب من أعمال الصلاة الأساسية. لا يعوّض سجود السهو ترك الركن نفسه.',evidence:'تعليم النبي ﷺ لمن لم يطمئن في صلاته',ref:'صحيح البخاري ٧٩٣ · صحيح مسلم ٣٩٧',note:'تختلف المذاهب في عدّ الأركان وبعض تفاصيل القراءة والتشهد؛ هذه خلاصة تعليمية وليست قائمة إجماع في جميع الجزئيات.'},
{id:'duties',section:'الصلاة',title:'الواجب والسنّة',text:'الركن لا يُجبر بمجرد سجود السهو. الحنابلة يميزون بين الأركان والواجبات والسنن: من الواجبات عندهم التشهد الأول والتكبيرات غير تكبيرة الإحرام. السنن كدعاء الاستفتاح لا تبطل الصلاة بتركها.',evidence:'سجود النبي ﷺ للسهو لما قام من الركعتين دون الجلوس',ref:'صحيح البخاري ١٢٢٤ · صحيح مسلم ٥٧٠',note:'مصطلح الواجب وتفاصيله هنا وفق العرض الحنبلي؛ الحنفية والشافعية والمالكية لهم تفصيل مختلف. لا يُقدّم هذا التقسيم كإجماع.'},
{id:'invalidators',section:'الصلاة',title:'مبطلات الصلاة',text:'من مبطلات الصلاة الحدث، وتعمد ترك ركن، والأكل والشرب عمدًا. الكلام الآدمي العمد لغير حاجة له أحكام مفصلة؛ أما السهو والجهل وحالات الضرورة فلا تُسوّى بالعمد.',evidence:'لا يقبل الله صلاة أحدكم إذا أحدث حتى يتوضأ',ref:'صحيح البخاري ١٣٥ · صحيح مسلم ٢٢٥',note:'تفاصيل الحركة والكلام وحالات العذر تُراجع في المذهب المتبع؛ لا تُحكم على صلاة شخص بمجرد هذا الملخص.'},
{id:'sahw',section:'الصلاة',title:'سجود السهو',text:'يشرع سجود السهو في حالات النقص والزيادة والشك. إذا شك المصلي في عدد الركعات ولم يترجح له شيء يبني على اليقين، ثم يسجد للسهو كما ورد في الحديث.',evidence:'حديث أبي سعيد في الشك في الصلاة',ref:'صحيح مسلم ٥٧١',note:'موضع السجود قبل السلام أو بعده يختلف بحسب سبب السهو وتفصيل المذاهب؛ لا توجد قاعدة واحدة تغطي جميع الحالات.'},
{id:'wudu',section:'الطهارة',title:'الوضوء',text:'توضأ بماء طهور مع النية: اغسل الوجه، ثم اليدين إلى المرفقين، وامسح الرأس، واغسل الرجلين إلى الكعبين. وردت المضمضة والاستنشاق في صفة وضوء النبي ﷺ. لا تُسرف في الماء.',evidence:'آية الوضوء وحديث عثمان في صفته',ref:'المائدة ٦ · صحيح البخاري ١٥٩ · صحيح مسلم ٢٢٦',note:'حكم الترتيب والموالاة والنية والمضمضة يختلف في التفصيل بين المذاهب.'},
{id:'ghusl',section:'الطهارة',title:'الغسل',text:'الغسل من الجنابة يكون بنية رفع الحدث وتعميم البدن بالماء. في الصفة الكاملة يغسل اليدين وما أصابه الأذى، ويتوضأ، ثم يغسل الرأس والبدن.',evidence:'صفة غسل النبي ﷺ من الجنابة',ref:'صحيح البخاري ٢٤٨ · صحيح مسلم ٣١٦',note:'أحكام المضمضة والاستنشاق وتفاصيل الأعذار ترجع إلى المذهب المتبع.'},
{id:'tayammum',section:'الطهارة',title:'التيمم',text:'عند فقد الماء أو تعذر استعماله لعذر معتبر يُشرع التيمم بالصعيد الطيب ومسح الوجه واليدين. لا يكفي مجرد عدم الرغبة في استعمال الماء.',evidence:'آية التيمم وحديث عمار',ref:'المائدة ٦ · صحيح البخاري ٣٤٧ · صحيح مسلم ٣٦٨',note:'صفة المسح وشروط العذر وما ينقض التيمم لها تفصيل فقهي.'},
{id:'fast',section:'الصيام',title:'صيام رمضان',text:'صوم رمضان فرض على المسلم المستطيع. يمتنع الصائم عن المفطرات من الفجر إلى غروب الشمس. للمريض والمسافر رخصة الفطر والقضاء وفق أحكامهما.',evidence:'فرض الصيام وبيان زمنه والرخص',ref:'البقرة ١٨٣–١٨٧'},
{id:'forget',section:'الصيام',title:'النسيان أثناء الصيام',text:'من نسي وهو صائم فأكل أو شرب يتم صومه؛ ورد أنه إنما أطعمه الله وسقاه. التفريق بين العمد والنسيان أساسي.',evidence:'حديث أبي هريرة في الأكل ناسيًا',ref:'صحيح البخاري ١٩٣٣ · صحيح مسلم ١١٥٥'},
{id:'hajj',section:'الحج والعمرة',title:'الاستطاعة والإحرام',text:'الحج واجب على المستطيع. يبدأ النسك بالإحرام من الميقات، ثم يؤدي الحاج المناسك. الوقوف بعرفة ركن الحج، ولا يُغني عنه الطواف وحده.',evidence:'وجوب الحج على المستطيع؛ الأمر بإتمام الحج والعمرة',ref:'آل عمران ٩٧ · البقرة ١٩٦',note:'العمرة وعدّ واجبات النسك ومسائل الفدية فيها تفصيل وخلاف معتبر؛ هذه مقدمة لا دليل مناسك كامل.'},
{id:'zakat',section:'الزكاة والصدقة',title:'الزكاة ومصارفها',text:'الزكاة فريضة مالية لها شروط في المال والنصاب والحول بحسب نوعه، ومصارف محددة. الصدقة التطوعية أوسع. لا تعمم نسبة واحدة على جميع الأموال والمحاصيل.',evidence:'بيان مصارف الزكاة الثمانية',ref:'التوبة ٦٠'},
{id:'manners',section:'الأذكار والآداب',title:'الذكر والرفق',text:'أكثر من ذكر الله، وأحسن القول، وارفق بالناس. الذكر لا يقتصر على وقت محدد، والأذكار المقيدة تلتزم بمصادرها وأوقاتها.',evidence:'الأمر بالذكر الكثير؛ الأمر بحسن القول',ref:'الأحزاب ٤١–٤٢ · الإسراء ٥٣'},
{id:'daily',section:'الأحكام اليومية',title:'الأمانة والبيع',text:'أدِّ الأمانات وصدق في البيع ولا تغش. المعاملات تحتاج معرفة الشروط والرضا وترك الربا والغرر؛ عند عقد جديد أو مسألة معقدة اسأل أهل العلم.',evidence:'أداء الأمانات؛ تحريم الربا',ref:'النساء ٥٨ · البقرة ٢٧٥'}
];
type Question={id:string;prompt:string;options:string[];correct:number[];lesson:string;kind?:'multi'|'order'};
export const FIQH_QUESTIONS:Question[]=[
{id:'a',prompt:'كم عدد أركان الإسلام؟',options:['خمسة','ستة','سبعة'],correct:[0],lesson:'islam'},
{id:'b',prompt:'أي مما يلي ليس من أركان الإسلام؟',options:['الصلاة','الزكاة','صلاة الضحى'],correct:[2],lesson:'islam'},
{id:'c',prompt:'كم عدد أركان الإيمان؟',options:['أربعة','خمسة','ستة'],correct:[2],lesson:'iman'},
{id:'d',prompt:'الإحسان أن تعبد الله كأنك تراه. صح أم خطأ؟',options:['صح','خطأ'],correct:[0],lesson:'iman'},
{id:'e',prompt:'دخول وقت الصلاة يُصنّف ضمن:',options:['الشروط','السنن','المبطلات'],correct:[0],lesson:'conditions'},
{id:'f',prompt:'اختر شرطين لصحة الصلاة من الآتي:',options:['الطهارة','استقبال القبلة للقادر','دعاء الاستفتاح'],correct:[0,1],lesson:'conditions',kind:'multi'},
{id:'g',prompt:'أكمل: الصلاة كانت على المؤمنين كتابًا…',options:['موقوتًا','مفتوحًا','مؤجلًا'],correct:[0],lesson:'conditions'},
{id:'h',prompt:'هل تجبر سجدتا السهو ترك الركوع نفسه؟',options:['نعم','لا'],correct:[1],lesson:'pillars'},
{id:'i',prompt:'صلّى رجل دون طمأنينة في ركوعه؛ ماذا علّم حديث المسيء صلاته؟',options:['الطمأنينة مطلوبة','السرعة أفضل','يكفي الوقوف'],correct:[0],lesson:'pillars'},
{id:'j',prompt:'رتب هذه الأعمال داخل الركعة:',options:['السجود','الركوع','الرفع من الركوع'],correct:[1,2,0],lesson:'pillars',kind:'order'},
{id:'k',prompt:'وفق التقسيم الحنبلي المذكور في الدرس: التشهد الأول…',options:['واجب','مبطل','شرط وقت'],correct:[0],lesson:'duties'},
{id:'l',prompt:'أي عبارة خاطئة؟',options:['تفاصيل المذاهب قد تختلف','كل المذاهب تستعمل تصنيف الواجب بنفس التفصيل','السنن لا تبطل الصلاة بتركها'],correct:[1],lesson:'duties'},
{id:'m',prompt:'من مبطلات الصلاة:',options:['الحدث','قراءة الفاتحة','الطمأنينة'],correct:[0],lesson:'invalidators'},
{id:'n',prompt:'شك المصلي في عدد الركعات دون ترجيح؛ يبني على…',options:['اليقين','أكبر عدد دائمًا','التخمين'],correct:[0],lesson:'sahw'},
{id:'o',prompt:'هل موضع سجود السهو قاعدة واحدة لجميع الحالات والمذاهب؟',options:['نعم','لا'],correct:[1],lesson:'sahw'},
{id:'p',prompt:'أكمل: تغسل اليدان في الوضوء إلى…',options:['المرفقين','الكتفين','الأصابع فقط'],correct:[0],lesson:'wudu'},
{id:'q',prompt:'أي عضو يُمسح في آية الوضوء؟',options:['الرأس','الوجه','الذراع'],correct:[0],lesson:'wudu'},
{id:'r',prompt:'رتب أعضاء الوضوء كما في الآية:',options:['الرجلان','الوجه','الرأس','اليدان'],correct:[1,3,2,0],lesson:'wudu',kind:'order'},
{id:'s',prompt:'الغسل يقتضي تعميم البدن بالماء. صح أم خطأ؟',options:['صح','خطأ'],correct:[0],lesson:'ghusl'},
{id:'t',prompt:'متى يشرع التيمم من الخيارات؟',options:['عند فقد الماء أو تعذر استعماله لعذر','عند الملل من الوضوء','دون أي عذر'],correct:[0],lesson:'tayammum'},
{id:'u',prompt:'اختر ما يُمسح في التيمم الوارد بالآية:',options:['الوجه','اليدان','الرجلان'],correct:[0,1],lesson:'tayammum',kind:'multi'},
{id:'v',prompt:'يبدأ الإمساك عن المفطرات من:',options:['الفجر','الظهر','الشروق'],correct:[0],lesson:'fast'},
{id:'w',prompt:'أكل صائم ناسيًا؛ ماذا يفعل؟',options:['يتم صومه','يفطر بقية اليوم','يترك الصلاة'],correct:[0],lesson:'forget'},
{id:'x',prompt:'اختر رخصتين منصوصتين في آيات الصيام:',options:['المرض','السفر','كثرة العمل بلا عذر'],correct:[0,1],lesson:'fast',kind:'multi'},
{id:'y',prompt:'الحج واجب على:',options:['المستطيع','الجميع بلا شرط','المسافر فقط'],correct:[0],lesson:'hajj'},
{id:'z',prompt:'هل الطواف يغني عن الوقوف بعرفة في الحج؟',options:['نعم','لا'],correct:[1],lesson:'hajj'},
{id:'aa',prompt:'مصارف الزكاة منصوص عليها في سورة:',options:['التوبة','الفيل','الإخلاص'],correct:[0],lesson:'zakat'},
{id:'ab',prompt:'الزكاة والصدقة التطوعية لهما كل الشروط نفسها. صح أم خطأ؟',options:['صح','خطأ'],correct:[1],lesson:'zakat'},
{id:'ac',prompt:'أيّها يوافق الآداب القرآنية؟',options:['حسن القول','الغش','إضاعة الأمانات'],correct:[0],lesson:'manners'},
{id:'ad',prompt:'طابق المفهوم: رد المال المحفوظ لصاحبه هو…',options:['أداء الأمانة','الغش','الربا'],correct:[0],lesson:'daily'}
];
function round(){let recent:string[]=[];try{recent=JSON.parse(localStorage.getItem('noor_fiqh_recent')||'[]')}catch{};const fresh=shuffleOrder(FIQH_QUESTIONS.filter(q=>!recent.includes(q.id)));const chosen=[...fresh,...shuffleOrder(FIQH_QUESTIONS.filter(q=>recent.includes(q.id)))].slice(0,10);try{localStorage.setItem('noor_fiqh_recent',JSON.stringify(chosen.map(q=>q.id)))}catch{};return chosen}
export function FiqhLearning({onBack}:{onBack:()=>void}){
 const [search,setSearch]=useState(''),[lesson,setLesson]=useState<Lesson|null>(null),[questions,setQuestions]=useState<Question[]|null>(null),[index,setIndex]=useState(0),[seconds,setSeconds]=useState(20),[selection,setSelection]=useState<number[]>([]),[checked,setChecked]=useState(false),[score,setScore]=useState(0);
 const question=questions?.[index],source=question&&LESSONS.find(l=>l.id===question.lesson);
 useEffect(()=>{if(!questions||!question||checked)return;const deadline=Date.now()+20000;setSeconds(20);const timer=window.setInterval(()=>{const left=Math.max(0,Math.ceil((deadline-Date.now())/1000));setSeconds(left);if(!left){setChecked(true);clearInterval(timer)}},100);return()=>clearInterval(timer)},[questions,index,checked]);
 function start(){setQuestions(round());setIndex(0);setSelection([]);setChecked(false);setScore(0)}
 const correct=question&&selection.length===question.correct.length&&(question.kind==='order'?selection.every((v,i)=>v===question.correct[i]):selection.every(v=>question.correct.includes(v)));
 function check(){if(checked)return;if(correct)setScore(n=>n+1);setChecked(true)}
 return <div className="fiqhLearning" dir="rtl"><button className="toolBack" onClick={()=>{if(questions){setQuestions(null);return}if(lesson){setLesson(null);return}onBack()}}>رجوع</button><header><h1>تفقّه في الدين</h1><p>تعلّم العبادات والأحكام الأساسية</p></header>{questions?(question?<section className="fiqhQuiz glassPanel"><small>السؤال {index+1} من ١٠ · {seconds} ثانية</small><progress aria-label="الوقت المتبقي" value={seconds} max={20}/><h2>{question.prompt}</h2>{question.kind==='multi'&&<p>اختر جميع الإجابات الصحيحة ثم تحقق.</p>}{question.kind==='order'&&<p>اضغط الخيارات بالترتيب. اضغط خيارًا محددًا لإزالته.</p>}<div className="fiqhOptions">{question.options.map((o,i)=><button key={o} disabled={checked} aria-pressed={selection.includes(i)} onClick={()=>setSelection(prev=>question.kind?prev.includes(i)?prev.filter(v=>v!==i):[...prev,i]:[i])}>{question.kind==='order'&&selection.includes(i)?`${selection.indexOf(i)+1} · `:''}{o}</button>)}</div>{!checked?<button className="primaryGlass" disabled={!selection.length} onClick={check}>تحقق</button>:<div role="status"><b>{seconds===0?'انتهى الوقت':correct?'إجابة صحيحة':'راجع الإجابة'}</b><p>الصحيح: {question.correct.map(i=>question.options[i]).join(' ← ')}</p><p>{source?.text}</p><small>المصدر: {source?.ref}</small><button className="primaryGlass" onClick={()=>{setIndex(n=>n+1);setSelection([]);setChecked(false)}}>{index===9?'عرض النتيجة':'السؤال التالي'}</button></div>}</section>:<section className="glassPanel fiqhResult"><h2>نتيجتك {score} / ١٠</h2><button className="primaryGlass" onClick={start}>جولة جديدة</button><button onClick={()=>setQuestions(null)}>الدروس</button></section>):lesson?<article className="fiqhLesson glassPanel"><img className="fiqhArt" src={FIQH_ART[lesson.section]} alt="تصوّر فني تعليمي"/><h2>{lesson.title}</h2><p>{lesson.text}</p><h3>الدليل</h3><p>{lesson.evidence}</p><small>{lesson.ref}</small>{lesson.note&&<aside>{lesson.note}</aside>}<a href="https://dorar.net/feqhia" target="_blank" rel="noreferrer">راجع الموسوعة الفقهية</a></article>:<><input className="featureSearch" aria-label="البحث في تفقّه في الدين" value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث عن درس أو حكم"/><button className="primaryGlass" onClick={start}>اختبار · ١٠ أسئلة</button><p className="featureNotice">الدروس والاختبارات تعمل دون إنترنت. هذه مقدمة تعليمية؛ تفاصيل الخلاف مبيّنة في الدروس.</p>{Array.from(new Set(LESSONS.map(l=>l.section))).map(section=>{const items=LESSONS.filter(l=>l.section===section&&normalizeArabicSearch(l.title+' '+l.text).includes(normalizeArabicSearch(search)));return items.length>0&&<section key={section}><img className="fiqhArt" src={FIQH_ART[section]} alt="تصوّر فني تعليمي"/><h2>{section}</h2><div className="fiqhLessons">{items.map(l=><button className="glassPanel" key={l.id} onClick={()=>setLesson(l)}>{l.title}<span>‹</span></button>)}</div></section>})}</>}</div>
}
