export type JourneyPlace={id:string;title:string;lat:number;lon:number;region:'hijaz'|'makkah';hint:string;context:string;source:string;url:string;stations:number[];labelOffset?:number};
export const ATLAS_BOUNDS={hijaz:[37,20.55,41.25,25.75],makkah:[39.72,21.29,40.05,21.53]} as const;
const mercator=(lat:number)=>Math.asinh(Math.tan(lat*Math.PI/180));
export function atlasPoint(lon:number,lat:number,region:keyof typeof ATLAS_BOUNDS){const [west,south,east,north]=ATLAS_BOUNDS[region];return {x:(lon-west)/(east-west)*100,y:(mercator(north)-mercator(lat))/(mercator(north)-mercator(south))*100};}
// Present-day approximate landmark points, not claims about the location of a whole surah's revelation.
export const JOURNEY_PLACES:JourneyPlace[]=[
 {id:'madinah',title:'المدينة',lat:24.4672,lon:39.6111,region:'hijaz',hint:'الهجرة وبناء المجتمع',context:'موضع تقريبي لوسط المدينة. يثبت خبر الهجرة الانتقال إليها؛ التصنيف المدني زمني، ولا يحدد مكان كل آية.',source:'OpenStreetMap · المدينة؛ صحيح البخاري ٣٩٠٥',url:'https://www.openstreetmap.org/?mlat=24.4672&mlon=39.6111#map=12/24.4672/39.6111',stations:[2,24],labelOffset:29},
 {id:'uhud',title:'أُحد',lat:24.5145,lon:39.6129,region:'hijaz',hint:'أُحد شمال المدينة',context:'نقطة تقريبية عند أُحد شمال المدينة. يربط التفسير آيات من آل عمران بأحداث القتال؛ ليست نسبة نزول السورة كلها إلى الجبل.',source:'روح السعودية · جبل أحد؛ تفسير ابن كثير ٣:١٢١',url:'https://www.visitsaudi.com/en/madinah/attractions/uhud-mountain-in-madinah',stations:[3],labelOffset:-32},
 {id:'badr',title:'بدر',lat:23.7843,lon:38.7891,region:'hijaz',hint:'بدر في القرآن',context:'بدر جنوب غربي المدينة. يذكرها القرآن صراحة في آل عمران ١٢٣؛ موقع المدينة الحديث هنا تقريبي ولا يحدد موضع نزول الآية.',source:'Apple Maps · إحداثيات بدر؛ آل عمران ١٢٣',url:'https://maps.apple.com/place?auid=6714180553538778548',stations:[3,8]},
 {id:'makkah',title:'مكة',lat:21.4225,lon:39.8262,region:'makkah',hint:'الدعوة والإنذار',context:'نقطة مرجعية عند الكعبة، لا حدود مكة القديمة. الأحداث المروية تتعلق بمواضع محددة؛ لا نجعل هذه النقطة مكان نزول كل السور المكية.',source:'OpenStreetMap · مكة؛ صحيح البخاري ٤٩٧١',url:'https://www.openstreetmap.org/?mlat=21.4225&mlon=39.8262#map=13/21.4225/39.8262',stations:[111,93]},
 {id:'hira',title:'حراء',lat:21.4574,lon:39.8592,region:'makkah',hint:'بدء الوحي',context:'حراء شمال شرقي الكعبة على جبل النور. يثبت حديث عائشة بدء الوحي في الغار؛ صورة المشهد تصور فني، وليست توثيقًا لهيئته أو أبعاده.',source:'OpenStreetMap · حراء؛ صحيح البخاري ٣',url:'https://www.openstreetmap.org/node/3732559985',stations:[96]},
 {id:'arafat',title:'عرفة',lat:21.3548,lon:39.9841,region:'makkah',hint:'آية إكمال الدين',context:'نقطة جغرافية قرب جبل الرحمة في عرفة شرقي مكة وجنوبها. الحديث يثبت نزول المائدة ٣ بعرفة، ولا يحدد النقطة الدقيقة داخل المشعر.',source:'Wikidata Q216894 · عرفة؛ صحيح البخاري ٤٥',url:'https://www.wikidata.org/wiki/Q216894',stations:[5]},
];
