export type JourneyEvidence={id:string;title:string;kind:'حدث عام'|'سياق نزول'|'سبب نزول'|'تفسير صحابي'|'قول تفسيري';text:string;source:string;url:string;surah?:number;from?:number;to?:number;place?:string;caution?:string};
export const JOURNEY_EVIDENCE:JourneyEvidence[]=[
 {id:'first',title:'بدء الوحي في حراء',kind:'سياق نزول',text:'يروي حديث عائشة بدء الوحي في غار حراء، واللقاء الذي نزل فيه افتتاح اقرأ. يثبت الخبر بداية الوحي، ولا يجعل آيات العلق التسع عشرة نازلة كلها في اللقاء نفسه.',source:'صحيح البخاري · ٣ · كتاب بدء الوحي',url:'https://sunnah.com/bukhari:3',surah:96,from:1,to:5,place:'hira'},
 {id:'safa',title:'الإنذار على الصفا',kind:'سبب نزول',text:'يربط حديث ابن عباس نداء الرسول لقومه على الصفا واعتراض أبي لهب بنزول تبت يدا أبي لهب. هذه صلة منصوصة في الحديث، وليست سببًا عامًا لكل سور الفترة المكية.',source:'صحيح البخاري · ٤٩٧١',url:'https://sunnah.com/bukhari:4971',surah:111,from:1,to:5,place:'makkah'},
 {id:'duha',title:'مواساة افتتاح الضحى',kind:'سبب نزول',text:'يذكر جندب مرض الرسول وتركه القيام ليلتين أو ثلاثًا، وكلام امرأة في ذلك، ثم نزول افتتاح الضحى. لا نضيف للرواية زمنًا أطول أو تفاصيل غير مذكورة.',source:'صحيح البخاري · ٤٩٥٠',url:'https://sunnah.com/bukhari:4950',surah:93,from:1,to:3,place:'makkah'},
 {id:'alaq-end',title:'منع الصلاة والطغيان',kind:'سياق نزول',text:'يروي أبو هريرة محاولة أبي جهل إيذاء الرسول وهو يصلي، ويربط سياق الخبر بآيات الطغيان والنهي عن الصلاة.',source:'صحيح مسلم · ٢٧٩٧',url:'https://sunnah.com/muslim:2797',surah:96,from:6,to:19,caution:'في لفظ مسلم تنبيه الراوي: لا ندري أهذا الربط من حديث أبي هريرة أم شيء بلغه؛ الخبر الصحيح لا يسوغ إخفاء هذا القيد.'},
 {id:'hijra',title:'الهجرة إلى المدينة',kind:'حدث عام',text:'يروي حديث عائشة الإذن بالهجرة وصحبة أبي بكر والمكث في غار ثور ثم السفر. الهجرة محطة للتمييز بين المكي والمدني، لا توقيتًا مفصلًا لنزول كل سورة.',source:'صحيح البخاري · ٣٩٠٥ · الهجرة',url:'https://sunnah.com/bukhari:3905',place:'madinah'},
 {id:'qibla',title:'تحويل القبلة',kind:'سياق نزول',text:'يروي البراء الصلاة نحو بيت المقدس ستة عشر أو سبعة عشر شهرًا، ثم التوجه إلى الكعبة، ويذكر آيتي القبلة وقبول الصلاة السابقة. نبقي الاختلاف في العدد كما ورد.',source:'صحيح البخاري · ٤٤٨٦',url:'https://sunnah.com/bukhari:4486',surah:2,from:142,to:144,place:'madinah'},
 {id:'anfal',title:'السؤال عن الأنفال',kind:'سبب نزول',text:'يروي سعد طلب سيف وامتناع الرسول عن إعطائه، ثم نزول يسألونك عن الأنفال. يخص الخبر افتتاح السورة؛ وليس رواية تفصيلية عن نزول جميع آياتها.',source:'صحيح مسلم · ١٧٤٨أ',url:'https://sunnah.com/muslim:1748a',surah:8,from:1,to:1},
 {id:'uhud',title:'العبرة من أُحد',kind:'قول تفسيري',text:'يشرح ابن كثير آية تبوئة المؤمنين للقتال بأنها أُحد عند جمهور المفسرين، في سياق اختبار المواقف والثبات. نعرضه بصفته تحديدًا تفسيريًا للحدث.',source:'تفسير ابن كثير · آل عمران ١٢١',url:'https://quran.ksu.edu.sa/tafseer/katheer/sura3-aya121.html',surah:3,from:121,to:155,place:'madinah'},
 {id:'ifk',title:'براءة عائشة والتثبت',kind:'سبب نزول',text:'تروي عائشة حادثة الإفك ونزول آيات تبرئتها. يعرض المقطع مسؤولية المجتمع في تداول الكلام ووجوب التثبت وحسن الظن، دون نقل القصة الطويلة كاملة.',source:'صحيح البخاري · ٤٧٥٠',url:'https://sunnah.com/bukhari:4750',surah:24,from:11,to:20,place:'madinah'},
 {id:'fath',title:'الحديبية ومعنى الفتح',kind:'سياق نزول',text:'يذكر ابن كثير نزول سورة الفتح عند الرجوع من الحديبية، ويشرح الفتح هنا بالصلح وما ترتب عليه. ويثبت حديث عمر نزول افتتاح السورة في السفر.',source:'تفسير ابن كثير · الفتح ١؛ وصحيح البخاري ٤٨٣٣',url:'https://quran.ksu.edu.sa/tafseer/katheer/sura48-aya1.html',surah:48,from:1,to:5,place:'makkah'},
 {id:'arafat',title:'إكمال الدين بعرفة',kind:'سياق نزول',text:'يشهد عمر في الحديث بأن آية إكمال الدين نزلت والرسول قائم بعرفة يوم الجمعة. يثبت مكان هذه الآية، مع كون المائدة مصنفة مدنية؛ فالتصنيف ليس عنوانًا جغرافيًا لكل آية.',source:'صحيح البخاري · ٤٥',url:'https://sunnah.com/bukhari:45',surah:5,from:3,to:3,place:'arafat'},
 {id:'tawba',title:'صدق الثلاثة وقبول التوبة',kind:'سبب نزول',text:'يروي كعب بن مالك ما حدث بعد تخلفه عن تبوك، ثم قبول توبة الثلاثة. ويشرح أن الذين خلفوا أُخّر الحكم في شأنهم، لا أن اللفظ مجرد تسمية لكل متخلف.',source:'صحيح البخاري · ٤٤١٨',url:'https://sunnah.com/bukhari:4418',surah:9,from:118,to:118,place:'madinah'},
 {id:'nasr',title:'قراءة ابن عباس لسورة النصر',kind:'تفسير صحابي',text:'فهم ابن عباس من السورة علامة قرب أجل الرسول، ووافقه عمر، مع أمر التسبيح والاستغفار. هذا تفسير منقول في الصحيح، وليس سببًا لادعاء تاريخ محدد لنزول كل آية.',source:'صحيح البخاري · ٤٩٧٠',url:'https://sunnah.com/bukhari:4970',surah:110,from:1,to:3},
 {id:'kawthar',title:'الكوثر في الرواية الصحيحة',kind:'سياق نزول',text:'يروي أنس أن الرسول أخبرهم بنزول السورة وفسر الكوثر بنهر أعطاه الله إياه. لا نُنشئ صورة تخمينية للنهر ولا نجزم بمكية السورة من هذا الخبر وحده.',source:'صحيح مسلم · ٤٠٠أ',url:'https://sunnah.com/muslim:400a',surah:108,from:1,to:3},
];
export const JOURNEY_DIFFERENCES:Record<number,Array<{source:string;text:string;url:string}>>={
 108:[{source:'Tanzil',text:'يعرضها الجدول مكية، في الترتيب الخامس عشر بحسب بدايات السور.',url:'https://tanzil.net/docs/revelation_order'},{source:'التحرير والتنوير · مقدمة الكوثر',text:'يعرض ابن عاشور اختلاف المكية والمدنية وما يستدل به لكل قول. لا تحول الواجهة أحد القولين إلى إجماع.',url:'https://www.islamweb.net/ar/library/content/61/4656/سورة-الكوثر'}],
 110:[{source:'Tanzil · مقارنة المنهجين',text:'النصر أخيرة في الجدول التقليدي؛ ويذكر المصدر أن نولدكه وضعها بين الحشر والنور. نحفظ ترتيب الجدول المعتمد ونظهر الخلاف.',url:'https://tanzil.net/docs/revelation_order'}],
 62:[{source:'Tanzil · مقارنة المنهجين',text:'الجمعة بعد التغابن والصف في الجدول التقليدي؛ ويذكر المصدر تقديمها عليهما في ترتيب نولدكه. المقارنة في ترتيب البداية، لا في ترتيب المصحف.',url:'https://tanzil.net/docs/revelation_order'}],
};
export const tafsirReferences=(surah:number,ayah:number)=>[
 {source:'السعدي',url:`https://quran.ksu.edu.sa/tafseer/saadi/sura${surah}-aya${ayah}.html`},
 {source:'ابن كثير',url:`https://quran.ksu.edu.sa/tafseer/katheer/sura${surah}-aya${ayah}.html`},
 {source:'الطبري',url:`https://quran.ksu.edu.sa/tafseer/tabary/sura${surah}-aya${ayah}.html`},
];
