import React,{useMemo,useRef,useState} from "react";
import {QURAN_STORIES} from "./quranStories";
import revelation from "./revelationData.json";
import type {RepeatSettings,SessionState} from "./recitationSession";
import {normalizeArabicSearch} from "./quranQuery";
export type FeatureVerse={verse_key:string;number:number;global_number:number;text:string;surahName:string;surahNumber:number};
export type FeatureSurah={number:number;name_arabic:string;counts:{ayahs:number};ayahs:Array<{verse_key:string;text:string}>};
const ar=(n:number)=>String(n).replace(/\d/g,d=>"٠١٢٣٤٥٦٧٨٩"[Number(d)]);
export function VerticalChoice({label,value,options,onChange}:{label:string;value:string;options:Array<{value:string;label:string}>;onChange:(value:string)=>void}){
 const [open,setOpen]=useState(false);
 return <div className="glassSelect"><span>{label}</span><button className="glassSelectControl" aria-haspopup="listbox" aria-expanded={open} onClick={()=>setOpen(!open)}>{options.find(o=>o.value===value)?.label||value}<span aria-hidden="true">⌄</span></button>{open&&<div className="glassSelectMenu selectionList" role="listbox" aria-label={label}>{options.map(o=><button role="option" aria-selected={o.value===value} key={o.value} className={o.value===value?"selected":""} onClick={()=>{onChange(o.value);setOpen(false)}}>{o.label}</button>)}</div>}</div>
}
export function RepeatPanel({surahs,settings,onSettings,state,onStart,onPause,onResume,onCancel,follow,onFollow}:{surahs:FeatureSurah[];settings:RepeatSettings;onSettings:(s:RepeatSettings)=>void;state:SessionState;onStart:()=>void;onPause:()=>void;onResume:()=>void;onCancel:()=>void;follow:boolean;onFollow:(v:boolean)=>void}){
 const s=surahs.find(s=>s.number===Number(settings.a.split(":")[0]))||surahs[0];if(!s)return null;
 const options=s.ayahs.map((v,i)=>({value:v.verse_key,label:`الآية ${ar(i+1)}`}));
 return <div className="sessionPanel glassPanel"><b>تكرار التلاوة A–B</b><VerticalChoice label="سورة المقطع" value={String(s.number)} options={surahs.map(s=>({value:String(s.number),label:s.name_arabic}))} onChange={v=>onSettings({...settings,a:`${v}:1`,b:`${v}:1`})}/><div className="sessionFields"><VerticalChoice label="البداية A" value={settings.a} options={options} onChange={a=>onSettings({...settings,a,b:Number(a.split(":")[1])>Number(settings.b.split(":")[1])?a:settings.b})}/><VerticalChoice label="النهاية B" value={settings.b} options={options.filter(o=>Number(o.value.split(":")[1])>=Number(settings.a.split(":")[1]))} onChange={b=>onSettings({...settings,b})}/><VerticalChoice label="عدد التكرارات" value={String(settings.count)} options={[0,1,2,3,5,10,20].map(n=>({value:String(n),label:n?ar(n):"مستمر"}))} onChange={n=>onSettings({...settings,count:Number(n)})}/><label>الفاصل بالثواني<input type="number" min="0" max="60" value={settings.gap} onChange={e=>onSettings({...settings,gap:Math.max(0,Math.min(60,Number(e.target.value)))})}/></label></div><label><span><input type="checkbox" checked={follow} onChange={e=>onFollow(e.target.checked)} style={{width:20,minHeight:20}}/> متابعة الآية مع الصوت</span></label><small role="status">{state.status==="idle"?"جاهز":state.status==="error"?state.message:`${({loading:"تحميل",playing:"تشغيل",paused:"متوقف مؤقتًا",waiting:"فاصل"} as const)[state.status]} · ${state.key} · التكرار ${ar(state.cycle)}`}</small><div className="sessionActions"><button onClick={onStart}>بدء التكرار</button>{state.status==="paused"?<button onClick={onResume}>استئناف</button>:<button disabled={state.status==="idle"||state.status==="error"} onClick={onPause}>إيقاف مؤقت</button>}<button onClick={onCancel}>إلغاء</button></div><small className="featureNotice">يعمل مع القارئ الحالي والملفات المحفوظة. يُحفظ المقطع والإعدادات، ويُوقف التكرار عند تغيير القارئ أو انتقال التطبيق للخلفية؛ استأنفه عند العودة.</small></div>
}
export function shuffleOrder<T>(items:T[],random= Math.random){const result=[...items];for(let i=result.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[result[i],result[j]]=[result[j],result[i]]}if(result.length>1&&result.every((v,i)=>v===items[i]))result.push(result.shift()!);return result}
export function OrderQuiz({verses,onScore}:{verses:FeatureVerse[];onScore:(results:Array<{key:string;correct:boolean}>)=>void}){
 const used=useRef(new Set<string>()),graded=useRef(false);const [cards,setCards]=useState<FeatureVerse[]>([]),[checked,setChecked]=useState(false),[revealed,setRevealed]=useState(false);const drag=useRef<number|null>(null);
 const expected=useMemo(()=>[...cards].sort((a,b)=>a.global_number-b.global_number),[cards]);
 function next(){const n=Math.min(5,verses.length);const candidates=Array.from({length:Math.max(0,verses.length-n+1)},(_,i)=>verses.slice(i,i+n)).filter(items=>!used.current.has(items.map(v=>v.verse_key).join(",")));if(!candidates.length){setCards([]);return}const chosen=candidates[Math.floor(Math.random()*candidates.length)];used.current.add(chosen.map(v=>v.verse_key).join(","));graded.current=false;setCards(shuffleOrder(chosen));setChecked(false);setRevealed(false)}
 function move(from:number,to:number){if(to<0||to>=cards.length||from===to)return;setCards(current=>{const next=[...current],item=next.splice(from,1)[0];next.splice(to,0,item);return next});setChecked(false)}
 return <div><p className="featureNotice">يستخدم النطاق المختار في مراجعة الحفظ. اسحب من المقبض أو استخدم زري التحريك. تُحسب المحاولة الأولى لكل مجموعة فقط.</p>{verses.length<2?<p>اختر آيتين على الأقل.</p>:!cards.length?<button className="primaryGlass" disabled={used.current.size>=Math.max(1,verses.length-Math.min(5,verses.length)+1)} onClick={next}>{used.current.size?"انتهت المجموعات في هذا النطاق":"ابدأ اختبار ترتيب الآيات"}</button>:<><ol className="orderList">{cards.map((v,i)=><li key={v.verse_key} data-order-index={i} className={checked?(v.verse_key===expected[i].verse_key?"correct":"incorrect"):""} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(drag.current!==null)move(drag.current,i);drag.current=null}}><button draggable onDragStart={()=>{drag.current=i}} onPointerDown={e=>{drag.current=i;e.currentTarget.setPointerCapture(e.pointerId)}} onPointerUp={e=>{const target=document.elementFromPoint(e.clientX,e.clientY)?.closest<HTMLElement>("[data-order-index]");if(target&&drag.current!==null)move(drag.current,Number(target.dataset.orderIndex));drag.current=null}} onPointerCancel={()=>drag.current=null} style={{touchAction:"none"}} aria-label={`سحب الآية في الموضع ${ar(i+1)}`}>⠿</button><p>{v.text}</p><div className="sessionActions"><button disabled={i===0} aria-label={`تحريك الآية في الموضع ${ar(i+1)} لأعلى`} onClick={()=>move(i,i-1)}>↑</button><button disabled={i===cards.length-1} aria-label={`تحريك الآية في الموضع ${ar(i+1)} لأسفل`} onClick={()=>move(i,i+1)}>↓</button>{checked&&<span>{v.verse_key===expected[i].verse_key?"موضع صحيح":"موضع غير صحيح"}</span>}</div></li>)}</ol><div className="sessionActions"><button onClick={()=>{setChecked(true);if(!graded.current){onScore(cards.map((v,i)=>({key:v.verse_key,correct:v.verse_key===expected[i].verse_key})));graded.current=true}}}>تحقق من الإجابة</button><button onClick={()=>{setChecked(false);setCards(shuffleOrder(expected));setRevealed(false)}}>إعادة المحاولة</button><button onClick={()=>{if(!graded.current){onScore(cards.map(v=>({key:v.verse_key,correct:false})));graded.current=true}setCards(expected);setChecked(true);setRevealed(true)}}>عرض الترتيب الصحيح</button><button onClick={next}>مجموعة جديدة</button></div>{revealed&&<p>هذا الترتيب الصحيح حسب أرقام الآيات.</p>}</>}</div>
}
export function RevelationJourney({surahs,onOpen}:{surahs:FeatureSurah[];onOpen:(key:string)=>void}){
 const [query,setQuery]=useState(""),[phase,setPhase]=useState("all"),[active,setActive]=useState<number|null>(null);
 const filtered=[...revelation.surahs].sort((a,b)=>a.order-b.order).filter(m=>(phase==="all"||m.type===phase)&&normalizeArabicSearch(surahs.find(s=>s.number===m.number)?.name_arabic||"").includes(normalizeArabicSearch(query)));
 return <><h2>رحلة نزول القرآن</h2><p className="featureNotice">ترتيب منقول لدى Tanzil، بحسب أوائل السور، وليس تاريخ اكتمال نزولها. التصنيف هنا بحسب هذا المصدر؛ قد تضم السورة آيات نزلت في مرحلة أخرى، والترتيب محل اختلاف علمي.</p><input className="featureSearch" aria-label="البحث في رحلة النزول" value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث عن سورة"/><div className="featureFilters">{[["all","الكل"],["Meccan","مكية"],["Medinan","مدنية"]].map(([v,label])=><button key={v} className={phase===v?"active":""} onClick={()=>setPhase(v)}>{label}</button>)}</div><details className="featureNotice"><summary>المصدر والاختلافات</summary><p>المرجع المحدد: جدول ترتيب النزول لدى Tanzil، الذي يعزو ترتيبه إلى «تاريخ القرآن» للزنجاني. من أمثلة الاختلاف: موضع سورتي النصر والجمعة في ترتيب نولدكه. لا نضيف سنوات أو أحداثًا لكل سورة بلا دليل.</p><a href={revelation.document} target="_blank" rel="noreferrer">جدول المصدر</a></details>{filtered.map(m=>{const s=surahs.find(s=>s.number===m.number);if(!s)return null;return <article className="featureCard timelineCard glassPanel" key={m.number}><button aria-expanded={active===m.number} onClick={()=>setActive(active===m.number?null:m.number)}>{ar(m.order)} · {s.name_arabic} · {m.type==="Meccan"?"مكية":"مدنية"}</button>{active===m.number&&<><small>{ar(s.counts.ayahs)} آية · رقمها في المصحف {ar(s.number)}</small>{m.number===96&&<p>افتتاح الوحي بآيات «اقرأ»: صحيح البخاري، كتاب بدء الوحي، الحديث ٣. أول السورة هنا لا يعني نزولها كاملة في ذلك الوقت.</p>}{m.number===48&&<p>ارتباط سورة الفتح بالرجوع من الحديبية: صحيح البخاري، كتاب المغازي، الحديث ٤١٧٧.</p>}<button onClick={()=>onOpen(`${s.number}:1`)}>افتح السورة في المصحف</button></>}</article>})}</>
}
export function QuranStories({surahs,onOpen}:{surahs:FeatureSurah[];onOpen:(key:string)=>void}){
 const [query,setQuery]=useState(""),[storyId,setStoryId]=useState<string|null>(null),[chapter,setChapter]=useState(0);const [progress,setProgress]=useState<Record<string,number>>(()=>{try{return JSON.parse(localStorage.getItem("noor_story_progress")||"{}")}catch{return {}}});const story=QURAN_STORIES.find(s=>s.id===storyId),event=story?.chapters[chapter];
 function save(n:number){if(!story)return;setChapter(n);const p={...progress,[story.id]:n};setProgress(p);localStorage.setItem("noor_story_progress",JSON.stringify(p))}
 return <><h2>قصص القرآن</h2>{!story?<><input className="featureSearch" aria-label="البحث في قصص القرآن" value={query} onChange={e=>setQuery(e.target.value)} placeholder="قصة أو نبي أو حدث"/>{QURAN_STORIES.filter(s=>normalizeArabicSearch([s.title,s.people,...s.chapters.map(c=>c.title)].join(" ")).includes(normalizeArabicSearch(query))).map(s=><article className="featureCard glassPanel" key={s.id}><button onClick={()=>{setStoryId(s.id);setChapter(Math.max(0,Math.min(s.chapters.length-1,progress[s.id]||0)))}}>{s.title}</button><small>{ar(s.chapters.length)} فصول · {progress[s.id]!==undefined?`متابعة من الفصل ${ar(progress[s.id]+1)}`:"لم تبدأ بعد"}</small></article>)}</>:event&&<><button className="toolBack" onClick={()=>setStoryId(null)}>رجوع إلى القصص</button><h3>{story.title}</h3><p className="featureNotice">السرد المختصر مستمد من الآيات المذكورة؛ الفصول روابط للقراءة ولا تحدد سنوات تاريخية.</p>{story.note&&<p className="featureNotice">{story.note}</p>}<div className="featureFilters">{story.chapters.map((c,i)=><button className={chapter===i?"active":""} key={i} onClick={()=>save(i)}>{ar(i+1)} · {c.title}</button>)}</div><article className="featureCard glassPanel"><h3>{event.title}</h3><p>{event.summary}</p><small>المصدر: القرآن الكريم · سورة {surahs.find(s=>s.number===event.surah)?.name_arabic}، {ar(event.from)}–{ar(event.to)}</small><button onClick={()=>onOpen(`${event.surah}:${event.from}`)}>افتح المقطع في المصحف</button><details><summary>عرض آيات الفصل</summary>{surahs.find(s=>s.number===event.surah)?.ayahs.slice(event.from-1,event.to).map(v=><button className="storyVerse" key={v.verse_key} onClick={()=>onOpen(v.verse_key)}>{v.text}</button>)}</details><div className="sessionActions"><button disabled={chapter===0} onClick={()=>save(chapter-1)}>السابق</button><button disabled={chapter===story.chapters.length-1} onClick={()=>save(chapter+1)}>التالي</button></div><small className="storyProgress">تم حفظ موضعك · {ar(chapter+1)}/{ar(story.chapters.length)}</small></article>{story.egypt&&<figure className="featureCard glassPanel"><svg viewBox="0 0 280 150" role="img" aria-label="دليل جغرافي تقريبي لمصر في شمال شرق إفريقيا"><rect width="280" height="150" fill="transparent"/><path d="M20 40L75 18L145 18L190 47L159 69L166 109L131 140L93 100L69 73L20 67Z" fill="rgba(80,150,112,.2)" stroke="currentColor"/><path d="M190 47L222 25L260 57L219 94L179 81Z" fill="rgba(80,150,112,.1)" stroke="currentColor"/><circle cx="153" cy="55" r="6" fill="#71b994"/><text x="150" y="34" textAnchor="middle" fill="currentColor" fontSize="13">مصر</text><text x="82" y="63" textAnchor="middle" fill="currentColor" fontSize="12">إفريقيا</text><text x="225" y="65" textAnchor="middle" fill="currentColor" fontSize="12">الجزيرة العربية</text></svg><figcaption className="featureNotice">خريطة توضيحية غير مقياسية لموضع مصر العام المذكورة في يوسف ٩٩، وليست تحديدًا لمواقع أحداث القصة.</figcaption></figure>}</>}</>
}
