import React,{useMemo,useRef,useState} from "react";
import {QURAN_STORIES} from "./quranStories";
import {SortableItems,validateRanks,rankNumber} from "./SortableItems";
import journeyTopics from "./journeyTopics.json";
import revelation from "./revelationData.json";
import type {RepeatSettings,SessionState} from "./recitationSession";
import {normalizeArabicSearch} from "./quranQuery";
export type FeatureVerse={verse_key:string;number:number;global_number:number;text:string;surahName:string;surahNumber:number};
export type FeatureSurah={number:number;name_arabic:string;counts:{ayahs:number};ayahs:Array<{verse_key:string;text:string}>};
const ar=(n:number)=>String(n).replace(/\d/g,d=>"٠١٢٣٤٥٦٧٨٩"[Number(d)]);
export function VerticalChoice({label,value,options,onChange}:{label:string;value:string;options:Array<{value:string;label:string}>;onChange:(value:string)=>void}){
 const [open,setOpen]=useState(false);
 return <div className="glassSelect"><span>{label}</span><button className="glassSelectControl" aria-haspopup="listbox" aria-expanded={open} onClick={()=>setOpen(!open)}>{options.find(o=>o.value===value)?.label||value}<span aria-hidden="true">⌄</span></button>{open&&<div className="glassSelectMenu selectionList" role="listbox" aria-label={label}>{options.map(o=><button role="option" aria-selected={o.value===value} key={o.value} className={o.value===value?"selected":""} onClick={()=>{onChange(o.value);setOpen(false)}}>{o.label}</button>)}</div>}</div>
}
export function RepeatPanel({surahs,settings,onSettings,state,onStart,onPause,onResume,onCancel,follow,onFollow}:{surahs:FeatureSurah[];settings:RepeatSettings;onSettings:(s:RepeatSettings)=>void;state:SessionState;onStart:()=>void;onPause:()=>void;onResume:()=>void;onCancel:()=>void;follow:boolean;onFollow:(v:boolean)=>void}){
 const s=surahs.find(s=>s.number===Number(settings.a.split(":")[0]))||surahs[0];if(!s)return null;
 const options=s.ayahs.map((v,i)=>({value:v.verse_key,label:`الآية ${ar(i+1)}`}));
 return <div className="sessionPanel glassPanel"><b>تكرار مقطع التلاوة</b><VerticalChoice label="سورة المقطع" value={String(s.number)} options={surahs.map(s=>({value:String(s.number),label:s.name_arabic}))} onChange={v=>onSettings({...settings,a:`${v}:1`,b:`${v}:1`})}/><div className="sessionFields"><VerticalChoice label="البداية A" value={settings.a} options={options} onChange={a=>onSettings({...settings,a,b:Number(a.split(":")[1])>Number(settings.b.split(":")[1])?a:settings.b})}/><VerticalChoice label="النهاية B" value={settings.b} options={options.filter(o=>Number(o.value.split(":")[1])>=Number(settings.a.split(":")[1]))} onChange={b=>onSettings({...settings,b})}/><VerticalChoice label="عدد التكرارات" value={String(settings.count)} options={[0,1,2,3,5,10,20].map(n=>({value:String(n),label:n?ar(n):"مستمر"}))} onChange={n=>onSettings({...settings,count:Number(n)})}/><label>الفاصل بالثواني<input type="number" min="0" max="60" value={settings.gap} onChange={e=>onSettings({...settings,gap:Math.max(0,Math.min(60,Number(e.target.value)))})}/></label></div><label><span><input type="checkbox" checked={follow} onChange={e=>onFollow(e.target.checked)} style={{width:20,minHeight:20}}/> متابعة الآية مع الصوت</span></label><small role="status">{state.status==="idle"?"جاهز":state.status==="error"?state.message:`${({loading:"تحميل",playing:"تشغيل",paused:"متوقف مؤقتًا",waiting:"فاصل"} as const)[state.status]} · ${state.key} · التكرار ${ar(state.cycle)}`}</small><div className="sessionActions"><button onClick={onStart}>بدء التكرار</button>{state.status==="paused"?<button onClick={onResume}>استئناف</button>:<button disabled={state.status==="idle"||state.status==="error"} onClick={onPause}>إيقاف مؤقت</button>}<button onClick={onCancel}>إلغاء</button></div><small className="featureNotice">يعمل مع القارئ الحالي والملفات المحفوظة. يُحفظ المقطع والإعدادات، ويُوقف التكرار عند تغيير القارئ أو انتقال التطبيق للخلفية؛ استأنفه عند العودة.</small></div>
}
export function shuffleOrder<T>(items:T[],random= Math.random){const result=[...items];for(let i=result.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[result[i],result[j]]=[result[j],result[i]]}if(result.length>1&&result.every((v,i)=>v===items[i]))result.push(result.shift()!);return result}
export function OrderQuiz({verses,onScore}:{verses:FeatureVerse[];onScore:(results:Array<{key:string;correct:boolean}>)=>void}){
 const used=useRef(new Set<string>()),graded=useRef(false);
 const [cards,setCards]=useState<FeatureVerse[]>([]),[ranks,setRanks]=useState<Record<string,string>>({}),[checked,setChecked]=useState(false),[revealed,setRevealed]=useState(false),[error,setError]=useState("");
 const expected=useMemo(()=>[...cards].sort((a,b)=>a.global_number-b.global_number),[cards]);
 function assign(items:FeatureVerse[]){setCards(items);setRanks(Object.fromEntries(items.map((v,i)=>[v.verse_key,String(i+1)])));setError("");setChecked(false);setRevealed(false)}
 function next(){const n=Math.min(5,verses.length),candidates=Array.from({length:Math.max(0,verses.length-n+1)},(_,i)=>verses.slice(i,i+n)).filter(items=>!used.current.has(items.map(v=>v.verse_key).join(",")));if(!candidates.length){setCards([]);return}const chosen=candidates[Math.floor(Math.random()*candidates.length)];used.current.add(chosen.map(v=>v.verse_key).join(","));graded.current=false;assign(shuffleOrder(chosen))}
 function ranked(){return [...cards].sort((a,b)=>rankNumber(ranks[a.verse_key])-rankNumber(ranks[b.verse_key]))}
 function commit(){if(!validateRanks(cards.map(v=>ranks[v.verse_key]),cards.length))assign(ranked())}
 function verify(){const invalid=validateRanks(cards.map(v=>ranks[v.verse_key]),cards.length);if(invalid){setError(invalid);return}const items=ranked();assign(items);setChecked(true);if(!graded.current){onScore(items.map((v,i)=>({key:v.verse_key,correct:v.verse_key===expected[i].verse_key})));graded.current=true}}
 return <div className="orderQuiz"><p className="featureNotice">اضغط مطولًا على البطاقة ثم اسحبها، أو أدخل ترتيبها أسفل الآية. للوحة المفاتيح: المسافة ثم الأسهم. تُحسب المحاولة الأولى لكل مجموعة.</p>{verses.length<2?<p>اختر آيتين على الأقل.</p>:!cards.length?<button className="primaryGlass" disabled={used.current.size>=Math.max(1,verses.length-Math.min(5,verses.length)+1)} onClick={next}>{used.current.size?"انتهت المجموعات في هذا النطاق":"ابدأ اختبار ترتيب الآيات"}</button>:<><SortableItems ids={cards.map(v=>v.verse_key)} onChange={ids=>assign(ids.map(id=>cards.find(v=>v.verse_key===id)!))} className="orderList" label="ترتيب الآيات">{id=>{const v=cards.find(v=>v.verse_key===id)!,i=cards.indexOf(v),correct=v.verse_key===expected[i].verse_key;return <article className={`orderVerseCard glassPanel ${checked?(correct?"correct":"incorrect"):""}`}><p>{v.text}</p><label className="verseRank">ترتيب الآية<input aria-label={`ترتيب الآية ${v.verse_key}`} inputMode="numeric" value={ranks[id]??""} onMouseDown={e=>e.stopPropagation()} onTouchStart={e=>e.stopPropagation()} onKeyDown={e=>{e.stopPropagation();if(e.key==="Enter")commit()}} onChange={e=>{setRanks({...ranks,[id]:e.target.value});setChecked(false);setError("")}} onBlur={commit}/></label>{checked&&<small>{correct?"موضع صحيح":"موضع غير صحيح"}</small>}</article>}}</SortableItems>{error&&<p role="alert">{error}</p>}<button className="primaryGlass orderVerify" onClick={verify}>تحقق من الإجابة</button>{checked&&<p role="status">{cards.every((v,i)=>v.verse_key===expected[i].verse_key)?"أحسنت، الترتيب صحيح.":"راجع مواضع الآيات، ويمكنك عرض الترتيب الصحيح."}</p>}<div className="sessionActions"><button onClick={()=>assign(shuffleOrder(expected))}>إعادة المحاولة</button>{checked&&!revealed&&<button onClick={()=>{assign(expected);setChecked(true);setRevealed(true)}}>عرض الترتيب الصحيح</button>}<button onClick={next}>مجموعة جديدة</button></div>{revealed&&<p>هذا الترتيب الصحيح حسب أرقام الآيات.</p>}</>}</div>
}
export function RevelationJourney({surahs,onOpen}:{surahs:FeatureSurah[];onOpen:(key:string)=>void}){
 const [query,setQuery]=useState(""),[phase,setPhase]=useState("all"),[active,setActive]=useState<number|null>(null);
 const [progress,setProgress]=useState<{visited:number[];last:number|null}>(()=>{try{const p=JSON.parse(localStorage.getItem("noor_journey_progress")||"{}");return {visited:Array.isArray(p.visited)?p.visited.filter((n:number)=>surahs.some(s=>s.number===n)):[],last:Number.isInteger(p.last)?p.last:null}}catch{return {visited:[],last:null}}});
 const list=useRef<HTMLDivElement>(null);
 const filtered=[...revelation.surahs].sort((a,b)=>a.order-b.order).filter(m=>(phase==="all"||m.type===phase)&&normalizeArabicSearch(surahs.find(s=>s.number===m.number)?.name_arabic||"").includes(normalizeArabicSearch(query)));
 function open(n:number){setActive(active===n?null:n);const p={visited:[...new Set([...progress.visited,n])],last:n};setProgress(p);localStorage.setItem("noor_journey_progress",JSON.stringify(p))}
 function resume(){setQuery("");setPhase("all");setActive(progress.last);requestAnimationFrame(()=>list.current?.querySelector(`[data-journey="${progress.last}"]`)?.scrollIntoView({block:"start",behavior:"smooth"}))}
 return <div className="journey"><h2>رحلة نزول القرآن</h2><p className="featureNotice">ترتيب بدايات نزول السور بحسب Tanzil، وليس تاريخ اكتمال نزولها. التصنيف منقول عن المصدر، وقد تضم السورة آيات من المرحلة الأخرى؛ توجد أقوال مختلفة.</p><div className="journeyProgress glassPanel"><label>استكشفت {ar(progress.visited.length)} من {ar(114)} سورة<progress max={114} value={progress.visited.length}/></label>{progress.last&&<button onClick={resume}>استئناف آخر موضع</button>}</div><div className="journeyControls"><input className="featureSearch" aria-label="البحث في رحلة النزول" value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث عن سورة"/><div className="featureFilters">{[["all","الكل"],["Meccan","مكية"],["Medinan","مدنية"]].map(([v,label])=><button key={v} aria-pressed={phase===v} className={phase===v?"active":""} onClick={()=>setPhase(v)}>{label}</button>)}</div></div><details className="featureNotice"><summary>المصدر والاختلافات</summary><p>ترتيب Tanzil المنقول عن «تاريخ القرآن» للزنجاني. يختلف ترتيب النصر والجمعة لدى نولدكه. النبذ أدناه تلخيص موضوعات من آيات محددة، ولا تمثل أسباب نزول أو تواريخ.</p><a href={revelation.document} target="_blank" rel="noreferrer">جدول ترتيب النزول وملاحظاته</a></details><div className="journeyTimeline" ref={list}>{filtered.map((m,i)=>{const s=surahs.find(s=>s.number===m.number);if(!s)return null;const topic=journeyTopics.find(t=>t.number===m.number)!;return <React.Fragment key={m.number}>{(i===0||filtered[i-1].type!==m.type)&&<h3 className={`journeyPhase ${m.type}`}><span aria-hidden="true">{m.type==="Meccan"?"◈":"◇"}</span>{m.type==="Meccan"?"المرحلة المكية":"المرحلة المدنية"}<small>بحسب تصنيف المصدر</small></h3>}<article data-journey={m.number} className={`featureCard timelineCard glassPanel ${m.type} ${progress.visited.includes(m.number)?"visited":""}`}><button className="journeyHeading" aria-expanded={active===m.number} onClick={()=>open(m.number)}><b>{ar(m.order)} · {s.name_arabic}</b><span>{m.type==="Meccan"?"مكية":"مدنية"}</span></button><small>ترتيب المصحف {ar(s.number)} · {ar(s.counts.ayahs)} آية</small>{active===m.number&&<><p>{topic.summary}</p><small>مصدر النبذة: القرآن الكريم · {topic.reference}</small>{"note" in m&&m.note&&<p className="featureNotice">ملاحظة المصدر (قول منقول): {String(m.note)}</p>}{[62,110].includes(m.number)&&<p className="featureNotice">موضع هذه السورة مختلف في ترتيب نولدكه؛ انظر جدول المصدر.</p>}<a href={revelation.document} target="_blank" rel="noreferrer">مصدر الترتيب والتصنيف</a><button onClick={()=>onOpen(`${s.number}:1`)}>افتح السورة في المصحف</button></>}</article></React.Fragment>})}{!filtered.length&&<p role="status">لا توجد سورة مطابقة.</p>}</div></div>
}
export function QuranStories({surahs,onOpen}:{surahs:FeatureSurah[];onOpen:(key:string)=>void}){
 const [query,setQuery]=useState(""),[storyId,setStoryId]=useState<string|null>(null),[chapter,setChapter]=useState(0);const [progress,setProgress]=useState<Record<string,number>>(()=>{try{return JSON.parse(localStorage.getItem("noor_story_progress")||"{}")}catch{return {}}});const story=QURAN_STORIES.find(s=>s.id===storyId),event=story?.chapters[chapter];
 function save(n:number){if(!story)return;setChapter(n);const p={...progress,[story.id]:n};setProgress(p);localStorage.setItem("noor_story_progress",JSON.stringify(p))}
 return <><h2>قصص القرآن</h2>{!story?<><input className="featureSearch" aria-label="البحث في قصص القرآن" value={query} onChange={e=>setQuery(e.target.value)} placeholder="قصة أو نبي أو حدث"/>{QURAN_STORIES.filter(s=>normalizeArabicSearch([s.title,s.people,...s.chapters.map(c=>c.title)].join(" ")).includes(normalizeArabicSearch(query))).map(s=><article className="featureCard glassPanel" key={s.id}><button onClick={()=>{setStoryId(s.id);setChapter(Math.max(0,Math.min(s.chapters.length-1,progress[s.id]||0)))}}>{s.title}</button><small>{ar(s.chapters.length)} فصول · {progress[s.id]!==undefined?`متابعة من الفصل ${ar(progress[s.id]+1)}`:"لم تبدأ بعد"}</small></article>)}</>:event&&<><button className="toolBack" onClick={()=>setStoryId(null)}>رجوع إلى القصص</button><h3>{story.title}</h3><p className="featureNotice">السرد المختصر مستمد من الآيات المذكورة؛ الفصول روابط للقراءة ولا تحدد سنوات تاريخية.</p>{story.note&&<p className="featureNotice">{story.note}</p>}<div className="featureFilters">{story.chapters.map((c,i)=><button className={chapter===i?"active":""} key={i} onClick={()=>save(i)}>{ar(i+1)} · {c.title}</button>)}</div><article className="featureCard glassPanel"><h3>{event.title}</h3><p>{event.summary}</p><small>المصدر: القرآن الكريم · سورة {surahs.find(s=>s.number===event.surah)?.name_arabic}، {ar(event.from)}–{ar(event.to)}</small><button onClick={()=>onOpen(`${event.surah}:${event.from}`)}>افتح المقطع في المصحف</button><details><summary>عرض آيات الفصل</summary>{surahs.find(s=>s.number===event.surah)?.ayahs.slice(event.from-1,event.to).map(v=><button className="storyVerse" key={v.verse_key} onClick={()=>onOpen(v.verse_key)}>{v.text}</button>)}</details><div className="sessionActions"><button disabled={chapter===0} onClick={()=>save(chapter-1)}>السابق</button><button disabled={chapter===story.chapters.length-1} onClick={()=>save(chapter+1)}>التالي</button></div><small className="storyProgress">تم حفظ موضعك · {ar(chapter+1)}/{ar(story.chapters.length)}</small></article>{story.egypt&&<figure className="featureCard glassPanel"><svg viewBox="0 0 280 150" role="img" aria-label="دليل جغرافي تقريبي لمصر في شمال شرق إفريقيا"><rect width="280" height="150" fill="transparent"/><path d="M20 40L75 18L145 18L190 47L159 69L166 109L131 140L93 100L69 73L20 67Z" fill="rgba(80,150,112,.2)" stroke="currentColor"/><path d="M190 47L222 25L260 57L219 94L179 81Z" fill="rgba(80,150,112,.1)" stroke="currentColor"/><circle cx="153" cy="55" r="6" fill="#71b994"/><text x="150" y="34" textAnchor="middle" fill="currentColor" fontSize="13">مصر</text><text x="82" y="63" textAnchor="middle" fill="currentColor" fontSize="12">إفريقيا</text><text x="225" y="65" textAnchor="middle" fill="currentColor" fontSize="12">الجزيرة العربية</text></svg><figcaption className="featureNotice">خريطة توضيحية غير مقياسية لموضع مصر العام المذكورة في يوسف ٩٩، وليست تحديدًا لمواقع أحداث القصة.</figcaption></figure>}</>}</>
}
