import React,{useMemo,useRef,useState} from "react";
import {SortableItems,validateRanks,rankNumber} from "./SortableItems";
import type {RepeatSettings,SessionState} from "./recitationSession";
import {normalizeArabicSearch} from "./quranQuery";
export type FeatureVerse={verse_key:string;number:number;global_number:number;text:string;surahName:string;surahNumber:number};
export type FeatureSurah={number:number;name_arabic:string;counts:{ayahs:number};ayahs:Array<{verse_key:string;text:string}>};
const ar=(n:number)=>String(n).replace(/\d/g,d=>"٠١٢٣٤٥٦٧٨٩"[Number(d)]);
export function VerticalChoice({label,value,options,onChange}:{label:string;value:string;options:Array<{value:string;label:string}>;onChange:(value:string)=>void}){
 const [open,setOpen]=useState(false);
 return <div className="glassSelect"><span>{label}</span><button className="glassSelectControl" aria-haspopup="listbox" aria-expanded={open} onClick={()=>setOpen(!open)}>{options.find(o=>o.value===value)?.label||value}<span aria-hidden="true">⌄</span></button>{open&&<div className="glassSelectMenu selectionList" role="listbox" aria-label={label}>{options.map(o=><button role="option" aria-selected={o.value===value} key={o.value} className={o.value===value?"selected":""} onClick={()=>{onChange(o.value);setOpen(false)}}>{o.label}</button>)}</div>}</div>
}
export function RepeatPanel({surahs,settings,onSettings,state,onStart,onPause,onResume,onCancel,follow,onFollow}:{surahs:FeatureSurah[];settings:RepeatSettings;onSettings:(s:RepeatSettings)=>void;state:SessionState;onStart:()=>void;onPause:()=>void;onResume:()=>void;onCancel:()=>void;follow:boolean;onFollow:(v:boolean)=>void}){
 const s=surahs.find(s=>s.number===Number(settings.a.split(":")[0]))||surahs[0];if(!s)return null;
 const options=s.ayahs.map((v,i)=>({value:v.verse_key,label:`الآية ${ar(i+1)}`}));
 return <div className="sessionPanel glassPanel"><b>تكرار مقطع التلاوة</b><VerticalChoice label="سورة المقطع" value={String(s.number)} options={surahs.map(s=>({value:String(s.number),label:s.name_arabic}))} onChange={v=>onSettings({...settings,a:`${v}:1`,b:`${v}:1`})}/><div className="sessionFields"><VerticalChoice label="البداية A" value={settings.a} options={options} onChange={a=>onSettings({...settings,a,b:Number(a.split(":")[1])>Number(settings.b.split(":")[1])?a:settings.b})}/><VerticalChoice label="النهاية B" value={settings.b} options={options.filter(o=>Number(o.value.split(":")[1])>=Number(settings.a.split(":")[1]))} onChange={b=>onSettings({...settings,b})}/><VerticalChoice label="عدد التكرارات" value={String(settings.count)} options={[0,1,2,3,5,10,20].map(n=>({value:String(n),label:n?ar(n):"مستمر"}))} onChange={n=>onSettings({...settings,count:Number(n)})}/><label>الفاصل بالثواني<input type="number" min="0" max="60" value={settings.gap} onChange={e=>onSettings({...settings,gap:Math.max(0,Math.min(60,Number(e.target.value)))})}/></label></div><label><span><input type="checkbox" checked={follow} onChange={e=>onFollow(e.target.checked)} style={{width:20,minHeight:20}}/> متابعة الآية مع الصوت</span></label><small role="status">{state.status==="idle"?"جاهز":state.status==="error"?state.message:`${({loading:"تحميل",playing:"تشغيل",paused:"متوقف مؤقتًا",waiting:"فاصل"} as const)[state.status]} · ${state.key} · التكرار ${ar(state.cycle)}`}</small><div className="sessionActions"><button onClick={onStart}>بدء التكرار</button>{state.status==="paused"?<button onClick={onResume}>استئناف</button>:<button disabled={state.status==="idle"||state.status==="error"} onClick={onPause}>إيقاف مؤقت</button>}<button onClick={onCancel}>إلغاء</button></div><small className="featureNotice">يعمل مع القارئ الحالي والملفات المحفوظة. يُحفظ المقطع والإعدادات، يتوقف عند تغيير القارئ. يعمل تكرار Android بخدمة وسائط؛ تكرار المتصفح قد يتوقف في الخلفية.</small></div>
}
export function shuffleOrder<T>(items:T[],random= Math.random){const result=[...items];for(let i=result.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[result[i],result[j]]=[result[j],result[i]]}if(result.length>1&&result.every((v,i)=>v===items[i]))result.push(result.shift()!);return result}
export function OrderQuiz({verses,allVerses=verses,onScore}:{verses:FeatureVerse[];allVerses?:FeatureVerse[];onScore:(results:Array<{key:string;correct:boolean}>)=>void}){
 const used=useRef(new Set<string>()),graded=useRef(false);
 const [difficulty,setDifficulty]=useState("easy"),[exhausted,setExhausted]=useState(false);
 const [cards,setCards]=useState<FeatureVerse[]>([]),[ranks,setRanks]=useState<Record<string,string>>({}),[checked,setChecked]=useState(false),[revealed,setRevealed]=useState(false),[error,setError]=useState("");
 const expected=useMemo(()=>[...cards].sort((a,b)=>a.global_number-b.global_number),[cards]);
 function assign(items:FeatureVerse[]){setCards(items);setRanks(Object.fromEntries(items.map((v,i)=>[v.verse_key,String(i+1)])));setError("");setChecked(false);setRevealed(false)}
 function next(){
 const pool=[...allVerses].sort((a,b)=>a.global_number-b.global_number), n=difficulty==="easy"?3+Math.floor(Math.random()*2):5+Math.floor(Math.random()*4);
 let recent:string[]=[];try{recent=JSON.parse(localStorage.getItem("noor_order_recent")||"[]")}catch{}
 const candidates=pool.map((v,i)=>{const available=pool.slice(i,i+n).filter(x=>x.surahNumber===v.surahNumber);return available}).filter(items=>items.length>=3&&items.every((v,i)=>v.surahNumber===items[0].surahNumber&&v.number===items[0].number+i)&&items.reduce((sum,v)=>sum+v.text.length,0)<2400);
 let available=candidates.filter(items=>!recent.includes(items.map(v=>v.verse_key).join(","))&&!used.current.has(items[0].verse_key));
 if(!available.length){if(candidates.length<=1){setCards([]);setExhausted(true);return}used.current.clear();available=candidates}
 if(!available.length){setError("لا توجد مقاطع مناسبة في البيانات الحالية");return}
 const chosen=available[Math.floor(Math.random()*available.length)],key=chosen.map(v=>v.verse_key).join(",");used.current.add(chosen[0].verse_key);try{localStorage.setItem("noor_order_recent",JSON.stringify([...recent,key].slice(-80)))}catch{}
 graded.current=false;assign(shuffleOrder(chosen));
 }
 function ranked(){return [...cards].sort((a,b)=>rankNumber(ranks[a.verse_key])-rankNumber(ranks[b.verse_key]))}
 function commit(){if(!validateRanks(cards.map(v=>ranks[v.verse_key]),cards.length))assign(ranked())}
 function verify(){const invalid=validateRanks(cards.map(v=>ranks[v.verse_key]),cards.length);if(invalid){setError(invalid);return}const items=ranked();assign(items);setChecked(true);if(!graded.current){onScore(items.map((v,i)=>({key:v.verse_key,correct:v.verse_key===expected[i].verse_key})));graded.current=true}}
 return <div className="orderQuiz"><label>المستوى<select value={difficulty} onChange={e=>{setDifficulty(e.target.value);setExhausted(false);used.current.clear()}}><option value="easy">سهل · ٣–٤ آيات</option><option value="hard">صعب · ٥–٨ آيات</option></select></label><p className="featureNotice">اضغط مطولًا على البطاقة ثم اسحبها، أو أدخل ترتيبها أسفل الآية. للوحة المفاتيح: المسافة ثم الأسهم. تُحسب المحاولة الأولى لكل مجموعة.</p>{verses.length<2?<p>اختر آيتين على الأقل.</p>:!cards.length?<button className="primaryGlass" disabled={exhausted} onClick={next}>{used.current.size?"انتهت المجموعات في هذا النطاق":"ابدأ اختبار ترتيب الآيات"}</button>:<><SortableItems ids={cards.map(v=>v.verse_key)} onChange={ids=>assign(ids.map(id=>cards.find(v=>v.verse_key===id)!))} className="orderList" label="ترتيب الآيات">{id=>{const v=cards.find(v=>v.verse_key===id)!,i=cards.indexOf(v),correct=v.verse_key===expected[i].verse_key;return <article className={`orderVerseCard glassPanel ${checked?(correct?"correct":"incorrect"):""}`}><p>{v.text}</p><label className="verseRank">ترتيب الآية<input aria-label={`ترتيب الآية ${v.verse_key}`} inputMode="numeric" value={ranks[id]??""} onMouseDown={e=>e.stopPropagation()} onTouchStart={e=>e.stopPropagation()} onKeyDown={e=>{e.stopPropagation();if(e.key==="Enter")commit()}} onChange={e=>{setRanks({...ranks,[id]:e.target.value});setChecked(false);setError("")}} onBlur={commit}/></label>{checked&&<small>{correct?"موضع صحيح":"موضع غير صحيح"}</small>}</article>}}</SortableItems>{error&&<p role="alert">{error}</p>}<button className="primaryGlass orderVerify" onClick={verify}>تحقق من الإجابة</button>{checked&&<p role="status">{cards.every((v,i)=>v.verse_key===expected[i].verse_key)?"أحسنت، الترتيب صحيح.":"راجع مواضع الآيات، ويمكنك عرض الترتيب الصحيح."}</p>}<div className="sessionActions"><button onClick={()=>assign(shuffleOrder(expected))}>إعادة المحاولة</button>{checked&&!revealed&&<button onClick={()=>{assign(expected);setChecked(true);setRevealed(true)}}>عرض الترتيب الصحيح</button>}<button onClick={next}>مجموعة عشوائية جديدة</button></div>{revealed&&<p>هذا الترتيب الصحيح حسب أرقام الآيات.</p>}</>}</div>
}
export {RevelationJourney} from './RevelationJourney';


export {QuranStories} from './QuranStories';
