// @vitest-environment jsdom
import React from "react";
import {afterEach,describe,expect,it,vi} from "vitest";
import {render,fireEvent,cleanup,screen} from "@testing-library/react";
import {readFileSync} from "node:fs";
import {RecitationSession} from "./recitationSession";
import {OrderQuiz,QuranStories,RevelationJourney,shuffleOrder,VerticalChoice} from "./NoorFeatures";
import {QURAN_STORIES} from "./quranStories";
import revelation from "./revelationData.json";
const quran=JSON.parse(readFileSync("public/data/quran.json","utf8"));
const verses=quran.surahs[0].ayahs.map((v:any)=>({...v,surahName:"الفاتحة",surahNumber:1}));
afterEach(()=>{cleanup();localStorage.clear();vi.useRealTimers()});
function session(){const transport={play:vi.fn(),stop:vi.fn(),pause:vi.fn(),resume:vi.fn()};return {transport,engine:new RecitationSession(transport,vi.fn())}}
describe("actual-event recitation sequencing",()=>{
 it("waits for prepared/playing and ignores unrelated or duplicate completion events",()=>{const {engine,transport}=session();engine.start(["1:1","1:2"],2,0);engine.ended("1:1");expect(transport.play).toHaveBeenCalledTimes(1);engine.started("1:1");engine.ended("9:1");engine.ended("1:1");engine.ended("1:1");expect(transport.play.mock.calls.map(c=>c[0])).toEqual(["1:1","1:2"])});
 it("repeats the complete A–B range exactly twice with a custom gap",()=>{vi.useFakeTimers();const {engine,transport}=session();engine.start(["1:1","1:2"],2,3);for(let cycle=0;cycle<2;cycle++){engine.started("1:1");engine.ended("1:1");engine.started("1:2");engine.ended("1:2");if(cycle===0){expect(engine.state.status).toBe("waiting");vi.advanceTimersByTime(2999);expect(transport.play).toHaveBeenCalledTimes(2);vi.advanceTimersByTime(1)}}expect(transport.play.mock.calls.map(c=>c[0])).toEqual(["1:1","1:2","1:1","1:2"]);expect(engine.state.status).toBe("idle")});
 it("supports one-ayah infinite repeat and cancels every pending callback",()=>{vi.useFakeTimers();const {engine,transport}=session();engine.start(["1:1"],0,1);for(let i=0;i<5;i++){engine.started("1:1");engine.ended("1:1");vi.advanceTimersByTime(1000)}expect(transport.play).toHaveBeenCalledTimes(6);engine.started("1:1");engine.ended("1:1");engine.cancel();vi.runAllTimers();expect(transport.play).toHaveBeenCalledTimes(6)});
 it("pauses while loading without advancing or falsely claiming playback",()=>{const {engine,transport}=session();engine.start(["1:1"],1,0);engine.pause();engine.started("1:1");expect(engine.state.status).toBe("paused");engine.resume();expect(engine.state.status).toBe("loading");expect(transport.resume).toHaveBeenCalledOnce();engine.started("1:1");expect(engine.state.status).toBe("playing")});
 it("retains the remaining repeat gap across pause and resume",()=>{vi.useFakeTimers();const {engine,transport}=session();engine.start(["1:1"],2,3);engine.started("1:1");engine.ended("1:1");vi.advanceTimersByTime(1000);engine.pause();vi.advanceTimersByTime(20000);expect(transport.play).toHaveBeenCalledTimes(1);engine.resume();vi.advanceTimersByTime(1999);expect(transport.play).toHaveBeenCalledTimes(1);vi.advanceTimersByTime(1);expect(transport.play).toHaveBeenCalledTimes(2)});
 it("halts on errors and allows a fresh session",()=>{const {engine,transport}=session();engine.start(["1:1"],0,0);engine.fail("missing file");engine.ended("1:1");expect(engine.state.status).toBe("error");expect(transport.play).toHaveBeenCalledTimes(1);engine.start(["2:1"],1,0);expect(engine.state.key).toBe("2:1")});
});
describe("Quran learning features",()=>{
 it("verifies all 114 sourced revelation entries against the actual dataset",()=>{expect(revelation.surahs).toHaveLength(114);expect(new Set(revelation.surahs.map(s=>s.order)).size).toBe(114);for(const s of quran.surahs){const m=revelation.surahs.find(m=>m.number===s.number)!;expect(m.order).toBe(s.revelation.order);expect(m.type).toBe(s.revelation.type)}});
 it("validates every story reference and preserves the exact Quran text",()=>{expect(QURAN_STORIES.length).toBe(15);for(const s of QURAN_STORIES)for(const c of s.chapters){const surah=quran.surahs[c.surah-1];expect(c.from).toBeGreaterThan(0);expect(c.to).toBeGreaterThanOrEqual(c.from);expect(c.to).toBeLessThanOrEqual(surah.ayahs.length);for(const v of surah.ayahs.slice(c.from-1,c.to))expect(v.verse_key).toBe(`${c.surah}:${v.number}`)}});
 it("shuffles duplicate-text verses by identity without dropping any item",()=>{const v=[{id:1,text:"x"},{id:2,text:"x"},{id:3,text:"x"}];const next=shuffleOrder(v,()=>.99);expect(new Set(next)).toEqual(new Set(v));expect(next).not.toEqual(v)});
 it("uses vertical options and selects without native dropdowns",()=>{const change=vi.fn();render(<VerticalChoice label="اختيار" value="1" options={[{value:"1",label:"واحد"},{value:"2",label:"اثنان"}]} onChange={change}/>);fireEvent.click(screen.getByRole("button",{name:/واحد/}));fireEvent.click(screen.getByRole("option",{name:"اثنان"}));expect(change).toHaveBeenCalledWith("2");expect(screen.queryByRole("listbox")).toBeNull()});
 it("grades only the first attempt and does not repeat the sole question",()=>{const score=vi.fn();render(<OrderQuiz verses={verses.slice(0,3)} onScore={score}/>);fireEvent.click(screen.getByRole("button",{name:"ابدأ اختبار ترتيب الآيات"}));fireEvent.click(screen.getByRole("button",{name:"تحقق من الإجابة"}));fireEvent.click(screen.getByRole("button",{name:"إعادة المحاولة"}));fireEvent.click(screen.getByRole("button",{name:"تحقق من الإجابة"}));fireEvent.click(screen.getByRole("button",{name:"عرض الترتيب الصحيح"}));expect(score).toHaveBeenCalledOnce();expect(score.mock.calls[0][0]).toHaveLength(3);fireEvent.click(screen.getByRole("button",{name:"مجموعة جديدة"}));expect((screen.getByRole("button",{name:"انتهت المجموعات في هذا النطاق"}) as HTMLButtonElement).disabled).toBe(true)});
 it("filters the sourced journey and opens the exact Quran location",()=>{const open=vi.fn();render(<RevelationJourney surahs={quran.surahs} onOpen={open}/>);fireEvent.change(screen.getByLabelText("البحث في رحلة النزول"),{target:{value:"العلق"}});fireEvent.click(screen.getByRole("button",{name:/١ · العلق/}));fireEvent.click(screen.getByRole("button",{name:"افتح السورة في المصحف"}));expect(open).toHaveBeenCalledWith("96:1")});
 it("persists story progress and opens the chapter from offline Quran data",()=>{const open=vi.fn();render(<QuranStories surahs={quran.surahs} onOpen={open}/>);fireEvent.click(screen.getByRole("button",{name:"يوسف عليه السلام"}));fireEvent.click(screen.getByRole("button",{name:"التالي"}));expect(JSON.parse(localStorage.getItem("noor_story_progress")!).yusuf).toBe(1);fireEvent.click(screen.getByRole("button",{name:"افتح المقطع في المصحف"}));expect(open).toHaveBeenCalledWith("12:19");fireEvent.click(screen.getByRole("button",{name:"رجوع إلى القصص"}));fireEvent.click(screen.getByRole("button",{name:"يوسف عليه السلام"}));expect(screen.getByRole("heading",{name:"الابتلاء والسجن"})).toBeTruthy()});
});
