import React,{useEffect,useRef,useState} from 'react';
import {ArrowRight,ArrowLeft,BookOpen,ChevronLeft} from 'lucide-react';
import {QURAN_STORIES} from './quranStories';
import type {FeatureSurah} from './NoorFeatures';
import {normalizeArabicSearch} from './quranQuery';
import {QuranVerseText} from './QuranVerseText';
import {STORY_ART,CHAPTER_ART} from './storyArt';
const ar=(n:number)=>String(n).replace(/\d/g,d=>'٠١٢٣٤٥٦٧٨٩'[Number(d)]);
const categories=[{id:'faith',title:'الإيمان والهداية',ids:['adam','ibrahim','maryam','kahf']},{id:'call',title:'الدعوة وموقف الأقوام',ids:['nuh','hud','salih','lut','shuaib']},{id:'patience',title:'الابتلاء والفرج',ids:['yusuf','musa','ayub','yunus']},{id:'lesson',title:'الشكر والعبرة',ids:['sulayman','garden','saba','dhulqarnayn','ukhdud','fil','two-gardens','qarun','sabbath']}];
function stored<T,>(key:string,fallback:T):T{try{const data=JSON.parse(localStorage.getItem(key)||'null');return data&&typeof data==='object'&&!Array.isArray(data)?data:fallback}catch{return fallback}}
function persist(key:string,value:unknown){try{localStorage.setItem(key,JSON.stringify(value))}catch{/* Reading remains available when storage is unavailable. */}}
function Art({src,alt}:{src:string;alt:string}){return <figure className="storyArt"><img src={src} alt={alt} loading="lazy" decoding="async"/><figcaption>تصوّر فني · لا يحدد موقعًا أو هيئة تاريخية</figcaption></figure>}
export function QuranStories({surahs,onOpen}:{surahs:FeatureSurah[];onOpen:(key:string)=>void}){
 const [query,setQuery]=useState(''),[category,setCategory]=useState('all'),[storyId,setStoryId]=useState<string|null>(null),[chapter,setChapter]=useState<number|null>(null);
 const [positions,setPositions]=useState<Record<string,number>>(()=>stored('noor_story_progress',{})),[visited,setVisited]=useState<Record<string,number[]>>(()=>stored('noor_story_visited',{}));
 const [chapterProgress,setChapterProgress]=useState(0);
 const root=useRef<HTMLDivElement>(null),listScroll=useRef(0),chapterScroll=useRef(0);
 const story=QURAN_STORIES.find(s=>s.id===storyId),event=story&&chapter!==null?story.chapters[chapter]:null;
 const opened=(id:string)=>Array.isArray(visited[id])?visited[id].filter((n,i,a)=>Number.isInteger(n)&&n>=0&&n<(QURAN_STORIES.find(s=>s.id===id)?.chapters.length||0)&&a.indexOf(n)===i):[];
 const last=(id:string,length:number)=>Number.isInteger(positions[id])?Math.max(0,Math.min(length-1,positions[id])):0;
 useEffect(()=>{const el=root.current?.closest('.content');if(el)el.scrollTop=storyId?(chapter===null?chapterScroll.current:0):listScroll.current},[storyId,chapter]);
 useEffect(()=>{const el=root.current?.closest('.content');if(!el||!story||chapter===null)return;const key=`noor_story_scroll_${story.id}_${chapter}`;let pos=0;try{pos=Number(localStorage.getItem(key)||0)}catch{};el.scrollTop=pos;const save=()=>{const range=el.scrollHeight-el.clientHeight;setChapterProgress(range>0?Math.min(1,el.scrollTop/range):1);try{localStorage.setItem(key,String(el.scrollTop))}catch{}};el.addEventListener('scroll',save,{passive:true});save();return()=>el.removeEventListener('scroll',save)},[storyId,chapter]);
 function select(id:string){listScroll.current=root.current?.closest('.content')?.scrollTop||0;chapterScroll.current=0;setStoryId(id);setChapter(null)}
 function read(n:number){if(!story)return;if(chapter===null)chapterScroll.current=root.current?.closest('.content')?.scrollTop||0;setChapter(n);const p={...positions,[story.id]:n};setPositions(p);persist('noor_story_progress',p);const v={...visited,[story.id]:Array.from(new Set([...opened(story.id),n]))};setVisited(v);persist('noor_story_visited',v)}
 const matches=QURAN_STORIES.filter(s=>normalizeArabicSearch([s.title,s.people,...s.chapters.map(c=>c.title)].join(' ')).includes(normalizeArabicSearch(query)));
 return <div className="stories50" ref={root} dir="rtl">
 {!story?<><header className="storiesMast"><span className="storyEyebrow">اقرأ وتأمل</span><h2>قصص القرآن</h2><p>قصص من الآيات، وفصول تقودك إلى مصدرها في المصحف.</p></header><input className="featureSearch" aria-label="البحث في قصص القرآن" value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث عن قصة أو حدث"/><div className="storyCategories" aria-label="تصنيف القصص"><button aria-pressed={category==='all'} onClick={()=>setCategory('all')}>كل القصص</button>{categories.map(c=><button key={c.id} aria-pressed={category===c.id} onClick={()=>setCategory(c.id)}>{c.title}</button>)}</div><p className="storySourceNote">تصنيف موضوعي، دون افتراض ترتيب زمني بين الأنبياء. الرسوم تصوّرات فنية، والنص القرآني هو مصدر السرد.</p>{categories.filter(c=>category==='all'||category===c.id).map(c=>{const stories=matches.filter(s=>c.ids.includes(s.id));return stories.length>0&&<section key={c.id} className="storyGroup"><h3>{c.title}</h3><div className="storyGrid">{stories.map(s=><article key={s.id} className="storyIndexCard glassPanel" onClick={()=>select(s.id)}><img src={STORY_ART[s.id].src} alt={STORY_ART[s.id].alt} loading="lazy" decoding="async"/><div className="storyCardCopy"><span className="storyEyebrow">{ar(s.chapters.length)} فصول</span><h4>{s.title}</h4><p>{s.chapters[0].summary}</p><div className="storyReadProgress"><progress max={s.chapters.length} value={opened(s.id).length}/><small>{opened(s.id).length?`فتحت ${ar(opened(s.id).length)} من ${ar(s.chapters.length)} فصول`:'ابدأ الاستكشاف'}</small></div><button aria-label={s.title} onClick={e=>{e.stopPropagation();select(s.id)}}>استكشف القصة<ChevronLeft size={18}/></button></div></article>)}</div></section>})}{!matches.some(s=>category==='all'||categories.find(c=>c.id===category)?.ids.includes(s.id))&&<p role="status">لا توجد قصص مطابقة.</p>}</>:<><button className="toolBack storyBack" onClick={()=>{if(chapter!==null)setChapter(null);else setStoryId(null)}}><ArrowRight size={18}/>{chapter!==null?'فصول القصة':'رجوع إلى القصص'}</button>
 {chapter===null?<><Art src={STORY_ART[story.id].src} alt={STORY_ART[story.id].alt}/><header className="storiesMast"><span className="storyEyebrow">{ar(story.chapters.length)} فصول · {ar(opened(story.id).length)} فصول فتحتها</span><h2>{story.title}</h2><p>مقاطع مختارة، مرتبة للقراءة وفق أحداث الآيات. لا تحدد سنوات أو ترتيبًا تاريخيًا للمقاطع المستقلة.</p></header>{story.note&&<p className="storySourceNote">{story.note}</p>}{positions[story.id]!==undefined&&<button className="storyResume" onClick={()=>read(last(story.id,story.chapters.length))}><BookOpen size={18}/>تابع من الفصل {ar(last(story.id,story.chapters.length)+1)}</button>}<ol className="storyChapterList">{story.chapters.map((c,i)=><li key={i}><button className="glassPanel" onClick={()=>read(i)}><span className="storyChapterNumber">{ar(i+1)}</span><span><b>{c.title}</b><small>سورة {surahs.find(s=>s.number===c.surah)?.name_arabic} · {ar(c.from)}–{ar(c.to)}{opened(story.id).includes(i)?' · فتحت هذا الفصل':''}</small></span><ChevronLeft size={18}/></button></li>)}</ol></>:event&&<article className="storyDetail"><progress className="chapterProgress" aria-label="تقدم قراءة الفصل" max={1} value={chapterProgress}/><header className="storiesMast"><span className="storyEyebrow">{story.title} · الفصل {ar(chapter+1)} من {ar(story.chapters.length)}</span><h2>{event.title}</h2></header>{CHAPTER_ART[`${story.id}:${chapter}`]&&<Art {...CHAPTER_ART[`${story.id}:${chapter}`]}/>}<section className="storyExplanation glassPanel"><h3>من أحداث الآيات</h3><p>{event.summary}</p><small>المصدر: القرآن الكريم · سورة {surahs.find(s=>s.number===event.surah)?.name_arabic}، الآيات {ar(event.from)}–{ar(event.to)}. هذا تلخيص للمعنى، وليس نصًا قرآنيًا.</small></section><section className="storyPassage glassPanel"><div className="storyPassageHead"><h3>آيات الفصل</h3><button onClick={()=>onOpen(`${event.surah}:${event.from}`)}><BookOpen size={17}/>فتح الآيات</button></div>{surahs.find(s=>s.number===event.surah)?.ayahs.slice(event.from-1,event.to).map((v,i)=><p className="storyQuran" key={v.verse_key}><QuranVerseText text={v.text} surah={event.surah} ayah={event.from+i}/><span className="storyVerseNumber"> ﴿{ar(event.from+i)}﴾</span></p>)}</section><details className="storyChapterIndex"><summary>فهرس الفصول</summary>{story.chapters.map((c,i)=><button key={i} onClick={()=>read(i)}>{ar(i+1)} · {c.title}</button>)}</details><nav className="storyChapterNav" aria-label="التنقل بين الفصول"><button disabled={chapter===0} onClick={()=>read(chapter-1)}><ArrowRight size={17}/>السابق</button><span>{ar(chapter+1)} / {ar(story.chapters.length)}</span><button disabled={chapter===story.chapters.length-1} onClick={()=>read(chapter+1)}>التالي<ArrowLeft size={17}/></button></nav><p className="storySourceNote">حُفظ موضعك. ترتيب الفصول للقراءة داخل هذه القصة، ولا يثبت تاريخًا للأحداث.</p></article>}</>}
 </div>;
}
