// @vitest-environment jsdom
import React from 'react';
import {describe,it,expect,vi,beforeAll,afterEach} from 'vitest';
import {render,screen,fireEvent,cleanup} from '@testing-library/react';
import {readFileSync} from 'node:fs';
import {RevelationJourney,cleanJourneyProgress} from './RevelationJourney';
import data from './journeyContent.json';
import metadata from './revelationData.json';
import {JOURNEY_EVIDENCE,JOURNEY_DIFFERENCES,tafsirReferences} from './journeyEvidence';
const q=JSON.parse(readFileSync('public/data/quran.json','utf8'));
beforeAll(()=>{vi.stubGlobal('requestAnimationFrame',(cb:FrameRequestCallback)=>setTimeout(cb,0));vi.stubGlobal('cancelAnimationFrame',clearTimeout)});
afterEach(()=>{cleanup();localStorage.clear()});
const mount=()=>render(<section className="content"><RevelationJourney surahs={q.surahs} onOpen={vi.fn()}/></section>);
describe('Release 48 meaningful journey coverage',()=>{
 it('covers all 114 with distinct substantive themes and valid exact Quran ranges',()=>{expect(data.surahs).toHaveLength(114);expect(new Set(data.surahs.map(s=>s.number)).size).toBe(114);const texts:string[]=[];for(const s of data.surahs){expect(s.themes.length).toBeGreaterThanOrEqual(2);for(const t of s.themes){expect(t.from).toBeGreaterThan(0);expect(t.to).toBeLessThanOrEqual(q.surahs[s.number-1].ayahs.length);expect(t.to).toBeGreaterThanOrEqual(t.from);expect(t.text.length).toBeGreaterThan(55);expect(t.source).toBe(`quran:${s.number}:${t.from}-${t.to}`);texts.push(t.text)}}expect(new Set(texts).size).toBe(texts.length)});
 it('keeps verified historical reports separate from thematic analysis and flags the Muslim narrator caveat',()=>{for(const e of JOURNEY_EVIDENCE){expect(['سبب نزول','سياق نزول','حدث عام','قول تفسيري','تفسير صحابي']).toContain(e.kind);expect(e.url.startsWith('https://')).toBe(true);if(e.surah)expect(e.to).toBeLessThanOrEqual(q.surahs[e.surah-1].ayahs.length)}expect(JOURNEY_EVIDENCE.find(e=>e.id==='alaq-end')?.caution).toContain('لا ندري');expect(JOURNEY_EVIDENCE.find(e=>e.id==='hijra')?.kind).toBe('حدث عام');expect(JOURNEY_DIFFERENCES[108]).toHaveLength(2);expect(tafsirReferences(96,1).map(r=>r.source)).toEqual(['السعدي','ابن كثير','الطبري'])});
 it('sanitizes old progress and malicious/stale storage without losing valid visits',()=>{expect(cleanJourneyProgress({visited:[96,96,-1,115,'2'],last:115,favorites:[2,2,114]})).toEqual({visited:[96],last:null,favorites:[2,114]});expect(cleanJourneyProgress(null).visited).toEqual([])});
 it.each([['العلق',96],['القصص',28],['النصر',110]])('opens a real detail page for %s with multiple topics, exact verse and sources', (name,n)=>{mount();fireEvent.change(screen.getByLabelText('البحث في رحلة النزول'),{target:{value:name}});fireEvent.click(screen.getByRole('button',{name:new RegExp(` · ${name}$`)}));expect(screen.getByRole('region',{name:`تفاصيل سورة ${name}`})).toBeTruthy();expect(screen.getByText('اقرأ السورة عبر موضوعاتها')).toBeTruthy();expect(screen.getByText(q.surahs[n-1].ayahs[data.surahs.find(s=>s.number===n)!.themes[0].from-1].text)).toBeTruthy();expect(screen.getAllByText('راجع تفسير هذا المقطع').length).toBeGreaterThanOrEqual(2);expect(screen.getByRole('link',{name:'مصدر الترتيب والتصنيف · Tanzil'}).getAttribute('href')).toBe(metadata.document)});
 it('supports bookmarks and progress, persists state and restores reader-return detail',()=>{const r=mount();fireEvent.change(screen.getByLabelText('البحث في رحلة النزول'),{target:{value:'العلق'}});fireEvent.click(screen.getByRole('button',{name:'١ · العلق'}));fireEvent.click(screen.getByRole('button',{name:'أضف للمفضلة'}));expect(JSON.parse(localStorage.getItem('noor_journey_progress')!).favorites).toEqual([96]);r.unmount();mount();expect(screen.getByRole('region',{name:'تفاصيل سورة العلق'})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'العودة إلى الرحلة'}));fireEvent.click(screen.getByRole('button',{name:'تقدمي'}));expect(screen.getAllByRole('button',{name:/العلق/}).length).toBe(2)});
 it('changes map location and displays sourced event rather than assigning all surahs to pins',()=>{mount();fireEvent.click(screen.getByRole('button',{name:'الخريطة'}));expect(screen.getByText('بدء الوحي في حراء')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'موضع عرفة'}));expect(screen.getByText('إكمال الدين بعرفة')).toBeTruthy();expect(screen.getByRole('link',{name:'صحيح البخاري · ٤٥'}).getAttribute('href')).toBe('https://sunnah.com/bukhari:45')});
 it('handles the native back event inside details before closing the tool',()=>{mount();fireEvent.change(screen.getByLabelText('البحث في رحلة النزول'),{target:{value:'العلق'}});fireEvent.click(screen.getByRole('button',{name:'١ · العلق'}));const e=new Event('noor-journey-back',{cancelable:true});fireEvent(window,e);expect(e.defaultPrevented).toBe(true);expect(screen.queryByRole('region',{name:'تفاصيل سورة العلق'})).toBeNull()});
});
