import React,{useEffect,useMemo,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,Check,ChevronLeft,Flag,Heart,MapPin,Route,Search,Sparkles} from 'lucide-react';
import type {FeatureSurah} from './NoorFeatures';
import revelation from './revelationData.json';
import topics from './journeyTopics.json';
import content from './journeyContent.json';
import {JOURNEY_EVIDENCE,JOURNEY_DIFFERENCES,tafsirReferences,type JourneyEvidence} from './journeyEvidence';
import {normalizeArabicSearch} from './quranQuery';
const ar=(n:number)=>String(n).replace(/\d/g,d=>'٠١٢٣٤٥٦٧٨٩'[Number(d)]);
const ids=new Set(revelation.surahs.map(s=>s.number));
const progressKey='noor_journey_progress',stateKey='noor_journey_view';
export function cleanJourneyProgress(p:any){const valid=(a:unknown)=>Array.isArray(a)?[...new Set(a.filter(n=>Number.isInteger(n)&&ids.has(n)))]:[];return {visited:valid(p?.visited) as number[],favorites:valid(p?.favorites) as number[],last:ids.has(p?.last)?p.last as number:null};}
function read(key:string){try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}}
function write(key:string,value:unknown){try{localStorage.setItem(key,JSON.stringify(value))}catch{/* Read-only/private storage must not block reading. */}}
function Scene({kind}:{kind:'hira'|'makkah'|'madinah'|'night'}){return <svg className={`journeyScene ${kind}`} viewBox="0 0 320 116" aria-hidden="true"><path d="M0 114V94Q90 32 173 77T320 69V116Z" fill="currentColor" opacity=".09"/><path d="M0 112L45 65L73 82L117 24L174 93L214 62L271 95L320 69" fill="none" stroke="currentColor" strokeWidth="1.5" opacity=".28"/>{kind==='hira'&&<path d="M94 75L116 44L134 74Z" fill="currentColor" opacity=".15"/>}{kind==='madinah'&&[60,249].map(x=><g key={x} stroke="currentColor" fill="none" opacity=".45"><path d={`M${x} 101q-2-20 0-42m0 6q-22-26-30-7m30 7q25-27 34-8m-34 5q0-31 14-30m-14 31q-7-32-20-29`}/></g>)}{kind==='night'&&<><circle cx="249" cy="29" r="13" fill="currentColor" opacity=".25"/><path d="M214 18v8m-4-4h8M58 32v8m-4-4h8" stroke="currentColor" opacity=".5"/></>}<path d="M28 110Q100 87 165 104T298 107" fill="none" stroke="currentColor" strokeDasharray="3 5" opacity=".3"/></svg>}
function Evidence({item,onOpen}:{item:JourneyEvidence;onOpen:(key:string)=>void}){return <article className="journeyEvidence"><span className="journeyEyebrow"><Flag size={14}/>{item.kind}</span><h3>{item.title}</h3><p>{item.text}</p>{item.caution&&<p className="journeyCaution">{item.caution}</p>}<a href={item.url} target="_blank" rel="noreferrer">{item.source}<ArrowLeft size={14}/></a>{item.surah&&<button className="journeyTextButton" onClick={()=>onOpen(`${item.surah}:${item.from}`)}>اقرأ الآيات {ar(item.from!)}{item.to!==item.from?`–${ar(item.to!)}`:''} في المصحف</button>}</article>}
export function RevelationJourney({surahs,onOpen}:{surahs:FeatureSurah[];onOpen:(key:string)=>void}){
 const initial=useRef(read(stateKey));
 const [mode,setMode]=useState<'journey'|'map'|'progress'>(['journey','map','progress'].includes(initial.current?.mode)?initial.current.mode:'journey');
 const [query,setQuery]=useState(typeof initial.current?.query==='string'?initial.current.query:''),[phase,setPhase]=useState(['all','Meccan','Medinan'].includes(initial.current?.phase)?initial.current.phase:'all');
 const [active,setActive]=useState<number|null>(ids.has(initial.current?.active)?initial.current.active:null),[sort,setSort]=useState<'revelation'|'mushaf'>(initial.current?.sort==='mushaf'?'mushaf':'revelation');
 const [progress,setProgress]=useState(()=>cleanJourneyProgress(read(progressKey))),[place,setPlace]=useState('hira');
 const root=useRef<HTMLDivElement>(null),listScroll=useRef(Number(initial.current?.scroll)||0),pendingScroll=useRef(Number(initial.current?.scroll)||0);
 const byId=useMemo(()=>new Map(surahs.map(s=>[s.number,s])),[surahs]);
 const saveView=(scroll:number,selected=active)=>write(stateKey,{mode,query,phase,active:selected,sort,scroll});
 const saveProgress=(next:typeof progress)=>{setProgress(next);write(progressKey,next)};
 const owner=()=>root.current?.closest('.content') as HTMLElement|null;
 useEffect(()=>{const scroller=owner();if(!scroller)return;let raf=0;const fn=()=>{if(active===null)listScroll.current=scroller.scrollTop;cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>saveView(active===null?scroller.scrollTop:listScroll.current))};scroller.addEventListener('scroll',fn,{passive:true});return()=>{scroller.removeEventListener('scroll',fn);cancelAnimationFrame(raf)}},[mode,query,phase,active,sort]);
 useEffect(()=>{saveView(listScroll.current);const raf=requestAnimationFrame(()=>{const scroller=owner();if(scroller)scroller.scrollTop=active!==null?0:pendingScroll.current});return()=>cancelAnimationFrame(raf)},[active,mode]);
 useEffect(()=>{const onBack=(e:Event)=>{if(active!==null){e.preventDefault();back()}};window.addEventListener('noor-journey-back',onBack);return()=>window.removeEventListener('noor-journey-back',onBack)},[active]);
 function open(n:number){listScroll.current=owner()?.scrollTop||0;saveProgress({...progress,visited:[...new Set([...progress.visited,n])],last:n});saveView(listScroll.current,n);setActive(n)}
 function back(){pendingScroll.current=listScroll.current;setActive(null)}
 function switchMode(next:typeof mode){pendingScroll.current=0;setActive(null);setMode(next);setQuery('');setPhase('all')}
 function toggleFavorite(n:number){saveProgress({...progress,favorites:progress.favorites.includes(n)?progress.favorites.filter(id=>id!==n):[...progress.favorites,n]})}
 function readVerse(key:string){saveView(listScroll.current);onOpen(key)}
 function resume(){if(progress.last)open(progress.last)}
 const ordered=useMemo(()=>[...revelation.surahs].sort((a,b)=>sort==='mushaf'?a.number-b.number:a.order-b.order),[sort]);
 const filtered=ordered.filter(m=>(phase==='all'||m.type===phase)&&normalizeArabicSearch(`${byId.get(m.number)?.name_arabic} ${topics.find(t=>t.number===m.number)?.summary}`).includes(normalizeArabicSearch(query)));
 const m=revelation.surahs.find(m=>m.number===active),s=active?byId.get(active):null,c=content.surahs.find(c=>c.number===active),topic=topics.find(t=>t.number===active);
 const places=[{id:'hira',title:'حراء',hint:'بدء الوحي',x:69,y:67},{id:'makkah',title:'مكة ومحيطها',hint:'الدعوة والإنذار',x:46,y:74},{id:'madinah',title:'المدينة',hint:'الهجرة وبناء المجتمع',x:47,y:21},{id:'arafat',title:'عرفة',hint:'آية إكمال الدين',x:74,y:84}];
 return <div className="journey journey48" ref={root}>
  <div className="journeyMast"><div><span className="journeyEyebrow">استكشاف · فهم · توثيق</span><h2>رحلة نزول القرآن</h2></div><Route aria-hidden="true"/></div>
  <div className="journeyModes" aria-label="أوضاع رحلة النزول">{[['journey','الرحلة'],['map','الخريطة'],['progress','تقدمي']].map(([v,label])=><button key={v} aria-pressed={mode===v} onClick={()=>switchMode(v as typeof mode)}>{label}</button>)}</div>
  <div className="journeyProgressLine"><span>استكشفت {ar(progress.visited.length)} من {ar(114)} سورة</span><progress max={114} value={progress.visited.length}/>{progress.last&&<button onClick={resume}>استئناف آخر موضع</button>}</div>
  {s&&m&&c&&topic?<section className="journeyDetail" aria-label={`تفاصيل سورة ${s.name_arabic}`}>
   <button className="journeyBack" onClick={back}><ArrowRight size={17}/>العودة إلى {mode==='progress'?'تقدمي':'الرحلة'}</button>
   <div className={`journeyDetailHero ${m.type}`}><span className="journeyEyebrow">{m.type==='Meccan'?'الفترة المكية':'الفترة المدنية'} · تصنيف الجدول</span><h1>سورة {s.name_arabic}</h1><p>{topic.summary}</p><Scene kind={m.type==='Meccan'?'makkah':'madinah'}/></div>
   <div className="journeyFacts"><div><span>في المصحف</span><b>{ar(s.number)}</b></div><div><span>بداية النزول</span><b>{ar(m.order)}</b></div><div><span>عدد الآيات</span><b>{ar(s.counts.ayahs)}</b></div></div>
   <div className="journeyDetailActions"><button onClick={()=>toggleFavorite(s.number)} aria-pressed={progress.favorites.includes(s.number)}><Heart size={17} fill={progress.favorites.includes(s.number)?'currentColor':'none'}/>{progress.favorites.includes(s.number)?'في مفضلتي':'أضف للمفضلة'}</button><button onClick={()=>readVerse(`${s.number}:1`)}><BookOpen size={17}/>افتح السورة في المصحف</button></div>
   <section className="journeyThemes"><span className="journeyEyebrow">المقاصد والمحاور</span><h2>اقرأ السورة عبر موضوعاتها</h2><p className="journeySmall">هذه قراءة موضوعية أصلية من نطاقات الآيات؛ ليست روايات أسباب نزول.</p>{c.themes.map((t,i)=><article key={t.from}><span className="themeNumber">{ar(i+1)}</span><div><h3>{t.title}</h3><p>{t.text}</p><button className="journeyTextButton" onClick={()=>readVerse(`${s.number}:${t.from}`)}>سورة {s.name_arabic} · الآيات {ar(t.from)}–{ar(t.to)}<ChevronLeft size={15}/></button><details><summary>راجع تفسير هذا المقطع</summary><div className="journeyReferences">{tafsirReferences(s.number,t.from).map(r=><a key={r.source} href={r.url} target="_blank" rel="noreferrer">{r.source} · الآية {ar(t.from)}</a>)}</div></details></div></article>)}</section>
   <section className="journeySelections"><span className="journeyEyebrow">من آيات السورة</span><h2>توقف وتأمل</h2>{c.themes.slice(0,2).map(t=><article key={t.from}><small>{t.title} · {s.number}:{t.from}</small><p className="journeyQuran">{s.ayahs[t.from-1]?.text}</p><button onClick={()=>readVerse(`${s.number}:${t.from}`)}>افتح الآية في المصحف<ArrowLeft size={16}/></button></article>)}</section>
   <section><span className="journeyEyebrow">التاريخ وسياق النزول</span><h2>ما الذي تثبته المراجع؟</h2>{JOURNEY_EVIDENCE.filter(e=>e.surah===s.number).length?JOURNEY_EVIDENCE.filter(e=>e.surah===s.number).map(e=><Evidence key={e.id} item={e} onOpen={readVerse}/>):<div className="journeyEvidence"><p>لا تضيف هذه النسخة رواية محققة لسبب نزول خاص بهذه السورة. موضوعات الآيات أعلاه مستمدة من النص؛ لا تحولها إلى قصة تاريخية ولا تعين لها سنة أو مكانًا بلا دليل.</p><p className="journeySmall">للتوسع يمكنك مراجعة التفاسير عند كل محور. وجود رواية في كتاب أسباب النزول وحده لا يكفي للحكم بصحتها.</p></div>}</section>
   <section className="journeyComparison"><h2>الترتيب والمصادر والأقوال</h2><p>موضعها {ar(s.number)} في المصحف، و{ar(m.order)} في جدول بداية النزول. ترتيب المصحف هو ترتيب القراءة الثابت هنا؛ والرحلة تساعد على دراسة بدايات النزول ولا تغير المصحف.</p><a href={revelation.document} target="_blank" rel="noreferrer">مصدر الترتيب والتصنيف · Tanzil</a>{'note' in m&&<p className="journeyCaution">{String(m.note)}</p>}{JOURNEY_DIFFERENCES[s.number]?.map((d,i)=><article key={i}><b>{d.source}</b><p>{d.text}</p><a href={d.url} target="_blank" rel="noreferrer">راجع القول في مصدره</a></article>)}<details><summary>كيف تقارن بين كتب التفسير؟</summary><p className="journeySmall">روابط السعدي وابن كثير والطبري تقود إلى الآية المحددة، وليست إعلانًا لاتفاقهم على كل رواية. السعدي يشرح المعنى، وقد تورد كتب الروايات أقوالًا تحتاج إلى فحص مستقل. نعرض اختلافًا محددًا حين تتوفر له مراجعة، دون ترجيح غير مسند.</p></details></section>
   <button className="journeyBottomBack" onClick={back}>العودة إلى موضعي في الرحلة<ArrowRight size={17}/></button>
  </section>:<>
   {mode==='journey'&&<>
    <div className="journeyIntro"><span className="journeyEyebrow">من بداية الوحي إلى اكتمال الرسالة</span><h1>كل محطة…<br/>تفتح لك معنى</h1><p>سِر بين سور القرآن، وافهم موضوعاتها وما ثبت من سياقها. لا يمثل المسار تاريخًا دقيقًا لكل سورة.</p><Scene kind="hira"/></div>
    <details className="journeyMethod"><summary>المصادر وطريقة قراءة الرحلة</summary><p>الترتيب لبدايات السور بحسب Tanzil. محطات الأحداث مواضع تعليمية ذات مراجع، وليست تأريخًا ملازمًا لموقعها بين السور. الملخصات الموضوعية من الآيات نفسها؛ الروايات الصحيحة مسماة، والأقوال التفسيرية متميزة.</p><a href={revelation.document} target="_blank" rel="noreferrer">جدول Tanzil وملاحظاته</a><p>نراجع السعدي وابن كثير والطبري والتحرير والتنوير عند المسائل المعروضة. لا تنقل هذه الرحلة كتبًا كاملة ولا تقدم روايات الواحدي والسيوطي بلا فحص أسانيدها.</p></details>
    <div className="journeyControls"><label className="journeySearch"><Search size={18}/><input aria-label="البحث في رحلة النزول" value={query} onChange={e=>setQuery(e.target.value)} placeholder="اسم سورة أو معنى…"/></label><div className="featureFilters">{[['all','الكل'],['Meccan','مكية'],['Medinan','مدنية']].map(([v,label])=><button key={v} aria-pressed={phase===v} className={phase===v?'active':''} onClick={()=>setPhase(v)}>{label}</button>)}</div><div className="journeySort"><span>قارن الترتيب</span><button aria-pressed={sort==='revelation'} onClick={()=>setSort('revelation')}>بداية النزول</button><button aria-pressed={sort==='mushaf'} onClick={()=>setSort('mushaf')}>ترتيب المصحف</button></div></div>
    <div className="journeyTimeline48">{!query&&phase==='all'&&sort==='revelation'&&<div className="journeyChapter"><span>الفصل الأول</span><h2>بداية الوحي</h2><Scene kind="hira"/><Evidence item={JOURNEY_EVIDENCE[0]} onOpen={readVerse}/></div>}{filtered.map((meta,i)=>{const surah=byId.get(meta.number),t=topics.find(t=>t.number===meta.number);if(!surah||!t)return null;const chapter=sort==='revelation'&&!query&&(i===0||filtered[i-1].type!==meta.type);return <React.Fragment key={meta.number}>{chapter&&meta.type==='Medinan'&&<div className="journeyChapter journeyHijra"><span>الفصل الثالث · الانتقال بين المرحلتين</span><Evidence item={JOURNEY_EVIDENCE.find(e=>e.id==='hijra')!} onOpen={readVerse}/></div>}{chapter&&<div className={`journeyChapter ${meta.type}`}><span>{meta.type==='Meccan'?'الفصل الثاني':'الفصل الرابع'}</span><h2>{meta.type==='Meccan'?'مكة · بناء الإيمان':'المدينة · بناء المجتمع'}</h2><p>{meta.type==='Meccan'?'التوحيد والبعث والقصص والصبر، مع تنوع موضوعات السور.':'العبادة والحقوق والأسرة والعلاقات، مع حضور التوحيد والآخرة.'}</p><Scene kind={meta.type==='Meccan'?'makkah':'madinah'}/></div>}{!query&&sort==='revelation'&&[111,2,3,48,5].includes(meta.number)&&<div className="journeyMilestone"><Evidence item={JOURNEY_EVIDENCE.find(e=>e.surah===meta.number)!} onOpen={readVerse}/></div>}<article data-journey={meta.number} className={`journeyStop ${meta.type} ${i%3===1?'insetStop':''} ${progress.visited.includes(meta.number)?'visited':''}`}><svg className="journeyPathSegment" viewBox="0 0 38 200" preserveAspectRatio="none" aria-hidden="true"><path d={i%2?'M18 0C-4 62 39 109 18 200':'M18 0C40 67-5 113 18 200'} fill="none" stroke="currentColor" strokeWidth="1.5" strokeDasharray="3 5"/></svg><span className="journeyStopNumber">{progress.visited.includes(meta.number)?<Check size={15}/>:ar(meta.order)}</span><button className="journeyHeading" aria-label={`${ar(meta.order)} · ${surah.name_arabic}`} onClick={()=>open(meta.number)}><span className="journeyEyebrow">{meta.type==='Meccan'?'مكية':'مدنية'} · {ar(surah.counts.ayahs)} آية</span><h3>{surah.name_arabic}</h3><p>{t.summary}</p><span className="journeyStopFoot">المصحف {ar(meta.number)}<span>اكتشف السورة<ChevronLeft size={14}/></span></span></button>{progress.favorites.includes(meta.number)&&<Heart size={14} className="journeyFavoriteMark" fill="currentColor"/>}</article></React.Fragment>})}{!filtered.length&&<p role="status">لا توجد سورة مطابقة.</p>}</div>
   </>}
   {mode==='map'&&<section className="journeyMapPage"><span className="journeyEyebrow">المكان والسياق</span><h1>أين تقع المحطات؟</h1><p>اختر موضعًا لتقرأ ما تثبته المراجع عن علاقته بالوحي.</p><div className="journeyMap"><svg viewBox="0 0 320 330" aria-hidden="true"><path d="M105 20L219 45L259 156L289 215L219 306L139 290L90 157Z" fill="currentColor" opacity=".06"/><path d="M135 21Q145 114 135 174T161 299" fill="none" stroke="currentColor" opacity=".18" strokeWidth="2"/><path d="M151 72Q175 178 144 248" stroke="currentColor" strokeDasharray="4 5" fill="none" opacity=".3"/><path d="M195 230L209 207L224 230M70 130L85 103L111 135" stroke="currentColor" fill="none" opacity=".16"/></svg>{places.map(p=><button key={p.id} style={{left:`${p.x}%`,top:`${p.y}%`}} aria-pressed={place===p.id} aria-label={`موضع ${p.title}`} onClick={()=>setPlace(p.id)}><MapPin size={18}/><span>{p.title}</span></button>)}<span className="journeyMapNorth">شمال ↑</span></div><p className="journeySmall">مخطط تعليمي غير مقياسي لمواضع عامة، وليس خريطة لمسار سفر تاريخي أو تعيينًا لمكان نزول كل سورة. الرسوم في الرحلة رمزية.</p><div className="journeyPlaceChoices">{places.map(p=><button aria-pressed={place===p.id} key={p.id} onClick={()=>setPlace(p.id)}>{p.title}</button>)}</div><h2>{places.find(p=>p.id===place)?.hint}</h2>{JOURNEY_EVIDENCE.filter(e=>e.place===place).map(e=><Evidence key={e.id} item={e} onOpen={readVerse}/>)}<p className="journeySmall">مكي ومدني تصنيف زمنـي قبل الهجرة وبعدها؛ لا يلزم منه أن كل آية نزلت داخل المدينة المسماة.</p></section>}
   {mode==='progress'&&<section className="journeyMyProgress"><span className="journeyEyebrow">سجل رحلتي</span><h1>المعاني التي زرتها</h1><div className="journeyStats"><div><b>{ar(progress.visited.length)}</b><span>سورة مستكشفة</span></div><div><b>{ar(progress.favorites.length)}</b><span>في مفضلتي</span></div><div><b>{ar(Math.round(progress.visited.length/114*100))}٪</b><span>من الرحلة</span></div></div><p className="journeySmall">الزيارة تسجل عند فتح التفاصيل؛ هذا مؤشر استكشاف، لا قياس للحفظ أو شهادة بإتمام قراءة السورة.</p><h2><Heart size={18}/>مفضلتي</h2>{!progress.favorites.length?<p>أضف سورة من صفحة تفاصيلها لتعود إلى معانيها بسهولة.</p>:progress.favorites.map(n=><button className="journeyRecord" key={n} onClick={()=>open(n)}><Heart size={17}/><b>{byId.get(n)?.name_arabic}</b><ChevronLeft size={17}/></button>)}<h2>السور التي زرتها</h2>{!progress.visited.length?<p>ابدأ من الرحلة، وافتح أول سورة ليظهر موضعك هنا.</p>:progress.visited.slice().reverse().map(n=><button className="journeyRecord" key={n} onClick={()=>open(n)}><Check size={17}/><b>{byId.get(n)?.name_arabic}</b><small>المصحف {ar(n)}</small><ChevronLeft size={17}/></button>)}</section>}
  </>}
 </div>;
}
