import {STORY_ART} from './storyArt';
import {QuranVerseText} from './QuranVerseText';
import React,{useEffect,useMemo,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,Check,ChevronLeft,Flag,Heart,MapPin,Route,Search,Sparkles,Compass} from 'lucide-react';
import type {FeatureSurah} from './NoorFeatures';
import revelation from './revelationData.json';
import topics from './journeyTopics.json';
import content from './journeyContent.json';
import {JOURNEY_EVIDENCE,JOURNEY_DIFFERENCES,tafsirReferences,type JourneyEvidence} from './journeyEvidence';
import {JourneyAtlas} from './JourneyAtlas';
import hiraArt from './assets/journey/hira.webp';
import makkahArt from './assets/journey/makkah.webp';
import madinahArt from './assets/journey/madinah.webp';
import travelArt from './assets/journey/travel.webp';
import {normalizeArabicSearch} from './quranQuery';
const ar=(n:number)=>String(n).replace(/\d/g,d=>'٠١٢٣٤٥٦٧٨٩'[Number(d)]);
const ids=new Set(revelation.surahs.map(s=>s.number));
const progressKey='noor_journey_progress',stateKey='noor_journey_view';
export function cleanJourneyProgress(p:any){const valid=(a:unknown)=>Array.isArray(a)?[...new Set(a.filter(n=>Number.isInteger(n)&&ids.has(n)))]:[];return {visited:valid(p?.visited) as number[],favorites:valid(p?.favorites) as number[],last:ids.has(p?.last)?p.last as number:null};}
function read(key:string){try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}}
function write(key:string,value:unknown){try{localStorage.setItem(key,JSON.stringify(value))}catch{/* Read-only/private storage must not block reading. */}}
const sceneAssets={hira:hiraArt,makkah:makkahArt,madinah:madinahArt,night:travelArt};
function Scene({kind}:{kind:keyof typeof sceneAssets}){return <img className={`journeyScene ${kind}`} src={sceneAssets[kind]} alt="" aria-hidden="true" loading="eager" decoding="async"/>}
const sceneFor=(n:number,type:string):keyof typeof sceneAssets=>n===96?'hira':n===73?'night':type==='Medinan'?'madinah':'makkah';
function Chapter({title,kicker,kind,children}:{title:string;kicker:string;kind:keyof typeof sceneAssets;children?:React.ReactNode}){return <section className="journeyChapter"><div className="journeyChapterArt"><Scene kind={kind}/><div><span>{kicker}</span><h2>{title}</h2></div><span className="artCaption">تصوّر فني</span></div>{children}</section>}

function Evidence({item,onOpen}:{item:JourneyEvidence;onOpen:(key:string)=>void}){return <article className="journeyEvidence"><span className="journeyEyebrow"><Flag size={14}/>{item.kind}</span><h3>{item.title}</h3><p>{item.text}</p>{item.caution&&<p className="journeyCaution">{item.caution}</p>}<a href={item.url} target="_blank" rel="noreferrer">{item.source}<ArrowLeft size={14}/></a>{item.surah&&<button className="journeyTextButton" onClick={()=>onOpen(`${item.surah}:${item.from}`)}>اقرأ الآيات {ar(item.from!)}{item.to!==item.from?`–${ar(item.to!)}`:''} في المصحف</button>}</article>}
export function RevelationJourney({surahs,onOpen}:{surahs:FeatureSurah[];onOpen:(key:string)=>void}){
 const initial=useRef(read(stateKey));
 const [mode,setMode]=useState<'journey'|'map'|'progress'>(['journey','map','progress'].includes(initial.current?.mode)?initial.current.mode:'journey');
 const [query,setQuery]=useState(typeof initial.current?.query==='string'?initial.current.query:''),[phase,setPhase]=useState(['all','Meccan','Medinan'].includes(initial.current?.phase)?initial.current.phase:'all');
 const [active,setActive]=useState<number|null>(ids.has(initial.current?.active)?initial.current.active:null),[sort,setSort]=useState<'revelation'|'mushaf'>(initial.current?.sort==='mushaf'?'mushaf':'revelation');
 const [progress,setProgress]=useState(()=>cleanJourneyProgress(read(progressKey))),[place,setPlace]=useState(['hira','makkah','madinah','uhud','badr','arafat'].includes(initial.current?.place)?initial.current.place:'hira');
 const [jump,setJump]=useState(''),[jumpError,setJumpError]=useState('');
 const root=useRef<HTMLDivElement>(null),listScroll=useRef(Number(initial.current?.scroll)||0),pendingScroll=useRef(Number(initial.current?.scroll)||0);
 const listAnchor=useRef<{id:number;offset:number}|null>(ids.has(initial.current?.anchor?.id)&&Number.isFinite(initial.current?.anchor?.offset)?initial.current.anchor:null);
 const byId=useMemo(()=>new Map(surahs.map(s=>[s.number,s])),[surahs]);
 const saveView=(scroll:number,selected=active)=>write(stateKey,{mode,query,phase,active:selected,sort,scroll,place,anchor:listAnchor.current});
 const saveProgress=(next:typeof progress)=>{setProgress(next);write(progressKey,next)};
 const owner=()=>root.current?.closest('.content') as HTMLElement|null;
 useEffect(()=>{const scroller=owner();if(!scroller)return;let raf=0;const fn=()=>{if(active===null){listScroll.current=scroller.scrollTop;listAnchor.current=null;}cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>saveView(active===null?scroller.scrollTop:listScroll.current))};scroller.addEventListener('scroll',fn,{passive:true});return()=>{scroller.removeEventListener('scroll',fn);cancelAnimationFrame(raf)}},[mode,query,phase,active,sort,place]);
 useEffect(()=>{saveView(listScroll.current);const raf=requestAnimationFrame(()=>{const scroller=owner();if(scroller){scroller.scrollTop=active!==null?0:pendingScroll.current;if(active===null&&listAnchor.current){const card=root.current?.querySelector(`[data-journey="${listAnchor.current.id}"]`);if(card)scroller.scrollTop+=card.getBoundingClientRect().top-scroller.getBoundingClientRect().top-listAnchor.current.offset}}});return()=>cancelAnimationFrame(raf)},[active,mode]);
 useEffect(()=>{const onBack=(e:Event)=>{if(active!==null){e.preventDefault();back()}};window.addEventListener('noor-journey-back',onBack);return()=>window.removeEventListener('noor-journey-back',onBack)},[active]);
 function open(n:number){const scroller=owner(),card=root.current?.querySelector(`[data-journey="${n}"]`);listScroll.current=scroller?.scrollTop||0;listAnchor.current=scroller&&card?{id:n,offset:card.getBoundingClientRect().top-scroller.getBoundingClientRect().top}:null;saveProgress({...progress,visited:[...new Set([...progress.visited,n])],last:n});saveView(listScroll.current,n);setActive(n)}
 function back(){pendingScroll.current=listScroll.current;setActive(null)}
 function switchMode(next:typeof mode){pendingScroll.current=0;listAnchor.current=null;setActive(null);setMode(next);setQuery('');setPhase('all')}
 function toggleFavorite(n:number){saveProgress({...progress,favorites:progress.favorites.includes(n)?progress.favorites.filter(id=>id!==n):[...progress.favorites,n]})}
 function readVerse(key:string){saveView(listScroll.current);onOpen(key)}
 function resume(){if(progress.last)open(progress.last)}
 function jumpToStation(e:React.FormEvent){e.preventDefault();const n=Number(jump.replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d))));const target=revelation.surahs.find(s=>s.order===n);if(!target){setJumpError('اختر رقمًا من ١ إلى ١١٤');return}setJumpError('');open(target.number)}
 const ordered=useMemo(()=>[...revelation.surahs].sort((a,b)=>sort==='mushaf'?a.number-b.number:a.order-b.order),[sort]);
 const filtered=ordered.filter(m=>(phase==='all'||m.type===phase)&&normalizeArabicSearch(`${byId.get(m.number)?.name_arabic} ${topics.find(t=>t.number===m.number)?.summary}`).includes(normalizeArabicSearch(query)));
 const m=revelation.surahs.find(m=>m.number===active),s=active?byId.get(active):null,c=content.surahs.find(c=>c.number===active),topic=topics.find(t=>t.number===active);

 return <div className="journey journey48 journey49" ref={root}>
  <div className="journeyMast"><div><h2>رحلة نزول القرآن</h2></div><Route aria-hidden="true"/></div>
  <div className="journeyModes" aria-label="أوضاع رحلة النزول">{[['journey','الرحلة'],['map','الخريطة'],['progress','تقدمي']].map(([v,label])=><button key={v} aria-pressed={mode===v} onClick={()=>switchMode(v as typeof mode)}>{v==='journey'?<Route size={17}/>:v==='map'?<Compass size={17}/>:<Check size={17}/>} {label}</button>)}</div>
  <div className="journeyProgressLine"><span>استكشفت {ar(progress.visited.length)} من {ar(114)} سورة</span><progress max={114} value={progress.visited.length}/>{progress.last&&<button onClick={resume}>استئناف آخر موضع</button>}</div>
  {s&&m&&c&&topic?<section className="journeyDetail" aria-label={`تفاصيل سورة ${s.name_arabic}`}>
   <button className="journeyBack" onClick={back}><ArrowRight size={17}/>العودة إلى {mode==='progress'?'تقدمي':mode==='map'?'الخريطة':'الرحلة'}</button>
   <div className={`journeyDetailHero ${m.type}`}><Scene kind={sceneFor(s.number,m.type)}/><div className="journeyHeroCopy"><span className="journeyEyebrow">{m.type==='Meccan'?'الفترة المكية':'الفترة المدنية'} · تصنيف الجدول</span><h1>سورة {s.name_arabic}</h1><p>{topic.summary}</p></div><span className="artCaption">تصوّر فني · لا توثيق أثري</span></div>
   <div className="journeyFacts"><div><span>في المصحف</span><b>{ar(s.number)}</b></div><div><span>ترتيب البداية</span><b>{ar(m.order)}</b></div><div><span>عدد الآيات</span><b>{ar(s.counts.ayahs)}</b></div></div>
   <div className="journeyDetailActions"><button onClick={()=>toggleFavorite(s.number)} aria-pressed={progress.favorites.includes(s.number)}><Heart size={17} fill={progress.favorites.includes(s.number)?'currentColor':'none'}/>{progress.favorites.includes(s.number)?'في مفضلتي':'أضف للمفضلة'}</button><button onClick={()=>readVerse(`${s.number}:1`)}><BookOpen size={17}/>افتح السورة في المصحف</button></div>
   <nav className="journeyDetailNav" aria-label="أقسام تفاصيل السورة">{[['journey-context','السياق'],['journey-topics','الموضوعات'],['journey-verses','الآيات'],['journey-sources','المراجع']].map(([id,label])=><button key={id} onClick={()=>root.current?.querySelector(`#${id}`)?.scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}>{label}</button>)}</nav>
   <section id="journey-context" className="journeyContextSection"><span className="journeyEyebrow">التاريخ وسياق النزول</span><h2>ما الذي تثبته المراجع؟</h2>{JOURNEY_EVIDENCE.filter(e=>e.surah===s.number).length?JOURNEY_EVIDENCE.filter(e=>e.surah===s.number).map(e=><Evidence key={e.id} item={e} onOpen={readVerse}/>):<div className="journeyEvidence"><p>لا تضيف هذه النسخة رواية محققة لسبب نزول خاص بهذه السورة. موضوعات الآيات أعلاه مستمدة من النص؛ لا تحولها إلى قصة تاريخية ولا تعين لها سنة أو مكانًا بلا دليل.</p><p className="journeySmall">للتوسع يمكنك مراجعة التفاسير عند كل محور. وجود رواية في كتاب أسباب النزول وحده لا يكفي للحكم بصحتها.</p></div>}</section>
   <section id="journey-topics" className="journeyThemes"><span className="journeyEyebrow">المقاصد والمحاور</span><h2>اقرأ السورة عبر موضوعاتها</h2><p className="journeySmall">هذه قراءة موضوعية أصلية من نطاقات الآيات؛ ليست روايات أسباب نزول.</p>{c.themes.map((t,i)=><article key={t.from}><span className="themeNumber">{ar(i+1)}</span><div><h3>{t.title}</h3><p>{t.text}</p><button className="journeyTextButton" onClick={()=>readVerse(`${s.number}:${t.from}`)}>سورة {s.name_arabic} · الآيات {ar(t.from)}–{ar(t.to)}<ChevronLeft size={15}/></button><details><summary>راجع تفسير هذا المقطع</summary><div className="journeyReferences">{tafsirReferences(s.number,t.from).map(r=><a key={r.source} href={r.url} target="_blank" rel="noreferrer">{r.source} · الآية {ar(t.from)}</a>)}</div></details></div></article>)}</section>
   <section id="journey-verses" className="journeySelections"><span className="journeyEyebrow">من آيات السورة</span><h2>توقف وتأمل</h2>{c.themes.slice(0,2).map(t=><article key={t.from}><small>{t.title} · {s.number}:{t.from}</small><p className="journeyQuran">{s.ayahs[t.from-1]&&<QuranVerseText text={s.ayahs[t.from-1].text} surah={s.number} ayah={t.from}/>}</p><button onClick={()=>readVerse(`${s.number}:${t.from}`)}>افتح الآية في المصحف<ArrowLeft size={16}/></button></article>)}</section>

   <section id="journey-sources" className="journeyComparison"><h2>الترتيب والمصادر والأقوال</h2><p>موضعها {ar(s.number)} في المصحف، و{ar(m.order)} في جدول بداية النزول. ترتيب المصحف هو ترتيب القراءة الثابت هنا؛ والرحلة تساعد على دراسة بدايات النزول ولا تغير المصحف.</p><a href={revelation.document} target="_blank" rel="noreferrer">مصدر الترتيب والتصنيف · Tanzil</a>{'note' in m&&<p className="journeyCaution">{String(m.note)}</p>}{JOURNEY_DIFFERENCES[s.number]?.map((d,i)=><article key={i}><b>{d.source}</b><p>{d.text}</p><a href={d.url} target="_blank" rel="noreferrer">راجع القول في مصدره</a></article>)}<details><summary>كيف تقارن بين كتب التفسير؟</summary><p className="journeySmall">روابط السعدي وابن كثير والطبري تقود إلى الآية المحددة، وليست إعلانًا لاتفاقهم على كل رواية. السعدي يشرح المعنى، وقد تورد كتب الروايات أقوالًا تحتاج إلى فحص مستقل. نعرض اختلافًا محددًا حين تتوفر له مراجعة، دون ترجيح غير مسند.</p></details></section>
   <button className="journeyBottomBack" onClick={back}>العودة إلى موضعي في الرحلة<ArrowRight size={17}/></button>
  </section>:<>
   {mode==='journey'&&<>
    <div className="journeyIntro"><Scene kind="hira"/><div className="journeyHeroCopy"><span className="journeyEyebrow">الفصل الأول · بدايات النزول</span><h1>بداية الوحي</h1><p>من «اقرأ»… إلى بناء الإيمان والمجتمع.</p></div><span className="artCaption">مشهد حراء · تصوّر فني</span></div>
    <details className="journeyOpening"><summary><Flag size={17}/> ما ثبت عن بدء الوحي</summary><Evidence item={JOURNEY_EVIDENCE[0]} onOpen={readVerse}/></details>
    <details className="journeyMethod"><summary>المصادر وطريقة قراءة الرحلة</summary><p>الترتيب لبدايات السور بحسب Tanzil. محطات الأحداث مواضع تعليمية ذات مراجع، وليست تأريخًا ملازمًا لموقعها بين السور. الملخصات الموضوعية من الآيات نفسها؛ الروايات الصحيحة مسماة، والأقوال التفسيرية متميزة.</p><a href={revelation.document} target="_blank" rel="noreferrer">جدول Tanzil وملاحظاته</a><p>نراجع السعدي وابن كثير والطبري والتحرير والتنوير عند المسائل المعروضة. لا تنقل هذه الرحلة كتبًا كاملة ولا تقدم روايات الواحدي والسيوطي بلا فحص أسانيدها.</p></details>
    <div className="journeyControls"><label className="journeySearch"><Search size={18}/><input aria-label="البحث في رحلة النزول" value={query} onChange={e=>setQuery(e.target.value)} placeholder="اسم سورة أو معنى…"/></label><div className="featureFilters">{[['all','الكل'],['Meccan','مكية'],['Medinan','مدنية']].map(([v,label])=><button key={v} aria-pressed={phase===v} className={phase===v?'active':''} onClick={()=>setPhase(v)}>{label}</button>)}</div><div className="journeySort"><span>قارن الترتيب</span><button aria-pressed={sort==='revelation'} onClick={()=>setSort('revelation')}>بداية النزول</button><button aria-pressed={sort==='mushaf'} onClick={()=>setSort('mushaf')}>ترتيب المصحف</button></div></div>
    <form className="journeyJump" onSubmit={jumpToStation}><label htmlFor="journey-jump">انتقل إلى محطة</label><input id="journey-jump" inputMode="numeric" maxLength={3} value={jump} onChange={e=>setJump(e.target.value)} placeholder="١–١١٤"/><button type="submit">انتقال<ChevronLeft size={16}/></button>{jumpError&&<p role="alert">{jumpError}</p>}</form>
    <div className="journeyTimeline48">{filtered.map((meta,i)=>{const thematicArt:Record<number,string>={71:'nuh',12:'yusuf',18:'kahf',34:'saba',27:'sulayman',19:'maryam',26:'musa',85:'ukhdud',105:'fil',28:'qarun',68:'garden',7:'sabbath',37:'ibrahim',15:'salih'};const art=thematicArt[meta.number];const surah=byId.get(meta.number),t=topics.find(t=>t.number===meta.number);if(!surah||!t)return null;const chapter=sort==='revelation'&&!query&&phase==='all';return <React.Fragment key={meta.number}>{art&&!query&&<figure className="journeyThemeArt"><img src={STORY_ART[art].src} alt={STORY_ART[art].alt} loading="lazy"/><figcaption>تصوّر فني من موضوعات سورة {surah.name_arabic} · ليس مكان نزولها</figcaption></figure>}{chapter&&meta.order===5&&<Chapter kicker="الفصل الثاني · قراءة موضوعية" title="مكة · بناء الإيمان" kind="makkah"/>}{chapter&&meta.order===87&&<><Chapter kicker="الفصل الثالث · حدث موثق" title="الهجرة إلى المدينة" kind="night"><details className="journeyOpening"><summary>اقرأ خبر الهجرة ومصدره</summary><Evidence item={JOURNEY_EVIDENCE.find(e=>e.id==='hijra')!} onOpen={readVerse}/></details></Chapter><Chapter kicker="الفصل الرابع · قراءة موضوعية" title="المدينة · بناء المجتمع" kind="madinah"/></>}{!query&&sort==='revelation'&&[111,2,3,48,5].includes(meta.number)&&<details className="journeyMilestone"><summary><Flag size={16}/>سياق موثق · {JOURNEY_EVIDENCE.find(e=>e.surah===meta.number)!.title}</summary><Evidence item={JOURNEY_EVIDENCE.find(e=>e.surah===meta.number)!} onOpen={readVerse}/></details>}<article data-journey={meta.number} className={`journeyStop ${meta.type} ${progress.last===meta.number?'currentStop':''} ${progress.visited.includes(meta.number)?'visited':''}`}><span className="journeyStopNumber" aria-label={`ترتيب النزول ${ar(meta.order)}`}>{ar(meta.order)}{progress.visited.includes(meta.number)&&<Check size={12} className="journeyVisitCheck"/>}</span><button className="journeyHeading" aria-label={`${ar(meta.order)} · ${surah.name_arabic}`} onClick={()=>open(meta.number)}><span className="journeyEyebrow">{meta.type==='Meccan'?'مكية':'مدنية'} · {ar(surah.counts.ayahs)} آية</span><h3>سورة {surah.name_arabic}</h3><p>{t.summary}</p><span className="journeyStopFoot"><span>اكتشف السورة<ChevronLeft size={14}/></span></span></button>{progress.favorites.includes(meta.number)&&<Heart size={14} className="journeyFavoriteMark" fill="currentColor"/>}</article></React.Fragment>})}{!filtered.length&&<p role="status">لا توجد سورة مطابقة.</p>}</div>
   </>}
   {mode==='map'&&<JourneyAtlas place={place} onPlace={id=>{setPlace(id);write(stateKey,{...read(stateKey),place:id})}} onStation={open} onEvidence={id=><Evidence key={id} item={JOURNEY_EVIDENCE.find(e=>e.id===id)!} onOpen={readVerse}/>}/>}
   {mode==='progress'&&<section className="journeyMyProgress"><div className="journeyProgressHero"><Scene kind="night"/><div className="journeyHeroCopy"><span className="journeyEyebrow">سجل رحلتي</span><h1>معانٍ… تبقى معك</h1></div></div><div className="journeyStats"><div><b>{ar(progress.visited.length)}</b><span>سورة مستكشفة</span></div><div><b>{ar(progress.favorites.length)}</b><span>في مفضلتي</span></div><div><b>{ar(Math.round(progress.visited.length/114*100))}٪</b><span>من الرحلة</span></div></div><p className="journeySmall">الزيارة تسجل عند فتح التفاصيل؛ هذا مؤشر استكشاف، لا قياس للحفظ أو شهادة بإتمام قراءة السورة.</p><h2><Heart size={18}/>مفضلتي</h2>{!progress.favorites.length?<p>أضف سورة من صفحة تفاصيلها لتعود إلى معانيها بسهولة.</p>:progress.favorites.map(n=><button className="journeyRecord" key={n} onClick={()=>open(n)}><Heart size={17}/><b>{byId.get(n)?.name_arabic}</b><ChevronLeft size={17}/></button>)}<h2>السور التي زرتها</h2>{!progress.visited.length?<p>ابدأ من الرحلة، وافتح أول سورة ليظهر موضعك هنا.</p>:progress.visited.slice().reverse().map(n=><button className="journeyRecord" key={n} onClick={()=>open(n)}><Check size={17}/><b>{byId.get(n)?.name_arabic}</b><small>المصحف {ar(n)}</small><ChevronLeft size={17}/></button>)}</section>}
  </>}
 </div>;
}
