import React,{useRef} from 'react';
import {DndContext,closestCenter,MouseSensor,TouchSensor,KeyboardSensor,useSensor,useSensors} from '@dnd-kit/core';
import {SortableContext,useSortable,rectSortingStrategy,verticalListSortingStrategy,sortableKeyboardCoordinates,arrayMove} from '@dnd-kit/sortable';
import {CSS} from '@dnd-kit/utilities';
export function mergeOrder(saved:unknown,ids:string[]){const clean=Array.isArray(saved)?saved.filter((id,i,a)=>typeof id==='string'&&ids.includes(id)&&a.indexOf(id)===i):[];return [...clean,...ids.filter(id=>!clean.includes(id))] as string[]}
function Item({id,children}:{id:string;children:React.ReactNode}){const {attributes,listeners,setNodeRef,transform,transition,isDragging}=useSortable({id});return <div ref={setNodeRef} {...attributes} {...listeners} role="listitem" aria-roledescription="بطاقة قابلة للترتيب" data-sort-id={id} className={`sortableCard ${isDragging?'dragging':''}`} style={{transform:CSS.Transform.toString(transform),transition,zIndex:isDragging?10:undefined}}>{children}</div>}
export function SortableItems({ids,onChange,children,className,grid=false,label}:{ids:string[];onChange:(ids:string[])=>void;children:(id:string)=>React.ReactNode;className:string;grid?:boolean;label:string}){
 const blocked=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const sensors=useSensors(useSensor(MouseSensor,{activationConstraint:{delay:350,tolerance:8}}),useSensor(TouchSensor,{activationConstraint:{delay:350,tolerance:8}}),useSensor(KeyboardSensor,{coordinateGetter:sortableKeyboardCoordinates}));
 function done(){if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>{blocked.current=false},400)}
 return <DndContext sensors={sensors} collisionDetection={closestCenter} autoScroll={{threshold:{x:.15,y:.18},acceleration:8}} accessibility={{screenReaderInstructions:{draggable:'لترتيب البطاقة اضغط المسافة، ثم الأسهم للتحريك، والمسافة للحفظ، أو Escape للإلغاء.'},announcements:{onDragStart:()=> 'بدأ تحريك البطاقة',onDragOver:({over})=>over?'تغير موضع البطاقة':undefined,onDragEnd:()=> 'تم حفظ الترتيب',onDragCancel:()=> 'أُلغي التحريك'}}} onDragStart={()=>{blocked.current=true;navigator.vibrate?.(18)}} onDragCancel={done} onDragEnd={({active,over})=>{if(over&&active.id!==over.id)onChange(arrayMove(ids,ids.indexOf(String(active.id)),ids.indexOf(String(over.id))));done()}}><SortableContext items={ids} strategy={grid?rectSortingStrategy:verticalListSortingStrategy}><div role="list" aria-label={label} className={className} onClickCapture={e=>{if(blocked.current){e.preventDefault();e.stopPropagation()}}}>{ids.map(id=><Item key={id} id={id}>{children(id)}</Item>)}</div></SortableContext></DndContext>
}
export function validateRanks(values:string[],n:number){const digits=(s:string)=>s.replace(/[٠-٩۰-۹]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.includes(d)?'٠١٢٣٤٥٦٧٨٩'.indexOf(d):'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)));const nums=values.map(s=>/^\d+$/.test(digits(s.trim()))?Number(digits(s.trim())):NaN);if(values.some(s=>!s.trim()))return 'أدخل ترتيب كل آية قبل التحقق.';if(nums.some(nr=>!Number.isInteger(nr)||nr<1||nr>n))return `استخدم أرقامًا صحيحة من ١ إلى ${n.toLocaleString('ar')} فقط.`;if(new Set(nums).size!==n)return 'يوجد ترتيب مكرر؛ أعطِ كل آية رقمًا مختلفًا.';return null}
export function rankNumber(s:string){return Number(s.replace(/[٠-٩۰-۹]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.includes(d)?'٠١٢٣٤٥٦٧٨٩'.indexOf(d):'۰۱۲۳۴۵۶۷۸۹'.indexOf(d))))}
