import React,{useEffect,useState} from 'react';
import type {FeatureSurah} from './NoorFeatures';
import {QuranVerseText} from './QuranVerseText';
const entries=[['2:153','كيف أستعين بالصبر والصلاة في موقف أواجهه؟'],['13:28','ما الوقت الذي أخصصه اليوم لذكر الله؟'],['94:5','ما باب الأمل الذي أراه رغم الصعوبة؟'],['49:13','كيف أتعامل باحترام مع من يختلف عني؟'],['17:23','ما الإحسان الذي أستطيع تقديمه لوالدي؟'],['39:53','ما الخطوة التي أبدأ بها التوبة اليوم؟'],['16:90','هل أعدِل في معاملتي للناس؟'],['3:134','كيف أضبط غضبي وأختار العفو؟'],['65:3','ما الأسباب التي آخذ بها مع التوكل؟'],['31:18','هل في سلوكي شيء من الكِبر يحتاج مراجعة؟'],['103:3','كيف أوصي نفسي بالحق والصبر؟'],['2:286','ما المسؤولية التي أقدر عليها اليوم؟']];
function choose(previous=''){let recent:string[]=[];try{recent=JSON.parse(localStorage.getItem('noor_tadabbur_recent')||'[]')}catch{};let available=entries.filter(e=>!recent.includes(e[0]));if(!available.length)available=entries.filter(e=>e[0]!==previous);const item=available[Math.floor(Math.random()*available.length)];try{localStorage.setItem('noor_tadabbur_recent',JSON.stringify([...recent,item[0]].slice(-entries.length+1)))}catch{};return item}
export function Tadabbur({surahs,onOpen,onSave,saved}:{surahs:FeatureSurah[];onOpen:(key:string)=>void;onSave:(key:string)=>void;saved:string[]}){
 const [item,setItem]=useState(()=>choose()),[tafsir,setTafsir]=useState<{type:string;text:string}|null>(null),[status,setStatus]=useState('');const [s,a]=item[0].split(':').map(Number),surah=surahs.find(v=>v.number===s),verse=surah?.ayahs[a-1];
 useEffect(()=>{let cancelled=false;setTafsir(null);setStatus('تحميل التفسير…');fetch(`./data/tafsir/${String(s).padStart(3,'0')}.json`).then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{if(cancelled)return;const v=data.ayahs.find((v:{ayah_number:number})=>v.ayah_number===a);const t=v?.tafsir.find((t:{type:string})=>t.type==='التفسير الميسر')||v?.tafsir[0];setTafsir(t||null);setStatus(t?'':'التفسير غير متاح لهذه الآية')}).catch(()=>{if(!cancelled)setStatus('تعذر تحميل التفسير المحلي')});return()=>{cancelled=true}},[item]);
 return <article className="tadabburPage"><h1>تدبّر آية</h1>{verse&&<section className="glassPanel"><p className="storyQuran"><QuranVerseText text={verse.text} surah={s} ayah={a}/></p><small>سورة {surah?.name_arabic} · الآية {a}</small></section>}<section className="glassPanel"><h2>التفسير</h2>{tafsir?<><p>{tafsir.text.length>650?tafsir.text.slice(0,650)+'…':tafsir.text}</p>{tafsir.text.length>650&&<details><summary>اقرأ التفسير كاملًا</summary><p>{tafsir.text}</p></details>}<small>المصدر: {tafsir.type} · النسخة المحلية</small></>:<p role="status">{status}</p>}</section><section className="glassPanel"><h2>سؤال للتأمل</h2><p>{item[1]}</p><small>سؤال تعليمي للتأمل، منفصل عن نص التفسير.</small></section><div className="sessionActions"><button onClick={()=>setItem(choose(item[0]))}>آية أخرى</button><button onClick={()=>onOpen(item[0])}>افتح في المصحف</button><button aria-pressed={saved.includes(item[0])} onClick={()=>onSave(item[0])}>{saved.includes(item[0])?'الآية محفوظة':'حفظ الآية'}</button></div></article>
}
