apply plugin: "com.android.application"

android {
    namespace "com.noor.quran"
    compileSdk 36

    defaultConfig {
        applicationId "com.noor.quran"
        minSdk 26
        targetSdk 36
        versionCode 48
        versionName "1.4.8"

    }


    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            debuggable false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging false
        }
    }
}

dependencies {
    implementation "com.batoulapps.adhan:adhan:1.2.1"
    implementation "androidx.core:core:1.13.1"
    implementation "com.microsoft.onnxruntime:onnxruntime-android:1.20.0"
}
